

package net.yezon.theabyss.init;

import net.yezon.theabyss.world.features.plants.YoungExoliusPlantFeature;
import net.yezon.theabyss.world.features.plants.WartRootFeature;
import net.yezon.theabyss.world.features.plants.WarpedCrystalOreFeature;
import net.yezon.theabyss.world.features.plants.VertaCelsiusFeature;
import net.yezon.theabyss.world.features.plants.VeraLesusFeature;
import net.yezon.theabyss.world.features.plants.VealusMeramusFeature;
import net.yezon.theabyss.world.features.plants.ThunderFlowerFeature;
import net.yezon.theabyss.world.features.plants.TeslaRankFeature;
import net.yezon.theabyss.world.features.plants.TenuemFireFeature;
import net.yezon.theabyss.world.features.plants.TantraGrassSmallFeature;
import net.yezon.theabyss.world.features.plants.TantraGrassMiddleFeature;
import net.yezon.theabyss.world.features.plants.TantraGrassBigFeature;
import net.yezon.theabyss.world.features.plants.TallRubShroomFeature;
import net.yezon.theabyss.world.features.plants.TallGlowShroomFeature;
import net.yezon.theabyss.world.features.plants.SralaShroomFeature;
import net.yezon.theabyss.world.features.plants.SlimedVitaeFeature;
import net.yezon.theabyss.world.features.plants.SlimedCarpetFeature;
import net.yezon.theabyss.world.features.plants.SaturniaVersaFeature;
import net.yezon.theabyss.world.features.plants.RubShroomFeature;
import net.yezon.theabyss.world.features.plants.RottenRankFeature;
import net.yezon.theabyss.world.features.plants.RaptorEggFeature;
import net.yezon.theabyss.world.features.plants.RalomPlantFeature;
import net.yezon.theabyss.world.features.plants.OpiaShroomFeature;
import net.yezon.theabyss.world.features.plants.OctavysMagynisiusFeature;
import net.yezon.theabyss.world.features.plants.MiniStone1Feature;
import net.yezon.theabyss.world.features.plants.LungoRankFeature;
import net.yezon.theabyss.world.features.plants.LumusMaximusFeature;
import net.yezon.theabyss.world.features.plants.LumusGrassFeature;
import net.yezon.theabyss.world.features.plants.LumusFlowerFeature;
import net.yezon.theabyss.world.features.plants.LumaGrassFeature;
import net.yezon.theabyss.world.features.plants.LoranFlowerFeature;
import net.yezon.theabyss.world.features.plants.LoranBushFeature;
import net.yezon.theabyss.world.features.plants.LoranBush2Feature;
import net.yezon.theabyss.world.features.plants.LercasUmbrellaFeature;
import net.yezon.theabyss.world.features.plants.LeraExiliarisFeature;
import net.yezon.theabyss.world.features.plants.LazarusGrassFeature;
import net.yezon.theabyss.world.features.plants.JungleLeaveCarpetFeature;
import net.yezon.theabyss.world.features.plants.IgnetarisVersaFeature;
import net.yezon.theabyss.world.features.plants.IcoraFlowerFeature;
import net.yezon.theabyss.world.features.plants.IcelaRankFeature;
import net.yezon.theabyss.world.features.plants.IceRankFeature;
import net.yezon.theabyss.world.features.plants.HollowCrystalOreFeature;
import net.yezon.theabyss.world.features.plants.GulomPlantFeature;
import net.yezon.theabyss.world.features.plants.GrassSmallFeature;
import net.yezon.theabyss.world.features.plants.GrassMiddleFeature;
import net.yezon.theabyss.world.features.plants.GrassBigFeature;
import net.yezon.theabyss.world.features.plants.GoralysLasusFeature;
import net.yezon.theabyss.world.features.plants.GlowingBlaruMossFeature;
import net.yezon.theabyss.world.features.plants.GlowShroomFeature;
import net.yezon.theabyss.world.features.plants.FrostCrystalOreFeature;
import net.yezon.theabyss.world.features.plants.FortisUltimaFeature;
import net.yezon.theabyss.world.features.plants.FlosVitaeFeature;
import net.yezon.theabyss.world.features.plants.ExoliusPlantFeature;
import net.yezon.theabyss.world.features.plants.EnderCrystalOreFeature;
import net.yezon.theabyss.world.features.plants.CrimsonCrystalOreFeature;
import net.yezon.theabyss.world.features.plants.CavernaCrystalOreFeature;
import net.yezon.theabyss.world.features.plants.CaecusVersaFeature;
import net.yezon.theabyss.world.features.plants.BlaruLeaveCarpetFeature;
import net.yezon.theabyss.world.features.plants.BlaruCaveMossFeature;
import net.yezon.theabyss.world.features.plants.AurelShroomFeature;
import net.yezon.theabyss.world.features.plants.AurelRankFeature;
import net.yezon.theabyss.world.features.plants.AurelLeaveCarpetFeature;
import net.yezon.theabyss.world.features.plants.AurelCrystalOreFeature;
import net.yezon.theabyss.world.features.plants.AurelCaveMossFeature;
import net.yezon.theabyss.world.features.plants.AnimaFireFeature;
import net.yezon.theabyss.world.features.plants.AbyssCrystalOreFeature;
import net.yezon.theabyss.world.features.ores.RomaMud2Feature;
import net.yezon.theabyss.world.features.ores.LoranOreFeature;
import net.yezon.theabyss.world.features.ores.IronVariantFeature;
import net.yezon.theabyss.world.features.ores.InfectedPeatFeature;
import net.yezon.theabyss.world.features.ores.InfectedGravelFeature;
import net.yezon.theabyss.world.features.ores.IncorytheOreFeature;
import net.yezon.theabyss.world.features.ores.IgnisitheOreFeature;
import net.yezon.theabyss.world.features.ores.GoldVariantFeature;
import net.yezon.theabyss.world.features.ores.GlacerytheOreFeature;
import net.yezon.theabyss.world.features.ores.GarniteOreFeature;
import net.yezon.theabyss.world.features.ores.FusionOreFeature;
import net.yezon.theabyss.world.features.ores.FloriteOreFeature;
import net.yezon.theabyss.world.features.ores.EmeraldVariantFeature;
import net.yezon.theabyss.world.features.ores.DiamondVariantFeature;
import net.yezon.theabyss.world.features.ores.DarkStoneFeature;
import net.yezon.theabyss.world.features.ores.AboranysOreFeature;
import net.yezon.theabyss.world.features.ores.AberytheOreFeature;
import net.yezon.theabyss.world.features.lakes.ArenoFeature;
import net.yezon.theabyss.world.features.WaterEcholotGroupMiddleFeature;
import net.yezon.theabyss.world.features.WartRankSmallFeature;
import net.yezon.theabyss.world.features.WartRankBigFeature;
import net.yezon.theabyss.world.features.TantraTreeRumaFeature;
import net.yezon.theabyss.world.features.TantraTreeFeature;
import net.yezon.theabyss.world.features.SlimedTentacleFeature;
import net.yezon.theabyss.world.features.SlimedRank3Feature;
import net.yezon.theabyss.world.features.SlimedRank2Feature;
import net.yezon.theabyss.world.features.SlimedRank1Feature;
import net.yezon.theabyss.world.features.SlimedGiantShroomFeature;
import net.yezon.theabyss.world.features.SlimedCraterFeature;
import net.yezon.theabyss.world.features.SlimeTreeFeature;
import net.yezon.theabyss.world.features.SlimeCrater2Feature;
import net.yezon.theabyss.world.features.SkelBoneFeature;
import net.yezon.theabyss.world.features.SalShroomFeature;
import net.yezon.theabyss.world.features.RumaLayingLogFeature;
import net.yezon.theabyss.world.features.RumaLayingLog3Feature;
import net.yezon.theabyss.world.features.RumaLayingLog2Feature;
import net.yezon.theabyss.world.features.RottenTreeFeature;
import net.yezon.theabyss.world.features.RottenTree2Feature;
import net.yezon.theabyss.world.features.RottenGiantShroomFeature;
import net.yezon.theabyss.world.features.RoggenTreeFeature;
import net.yezon.theabyss.world.features.RoggenTree3Feature;
import net.yezon.theabyss.world.features.RoggenTree2Feature;
import net.yezon.theabyss.world.features.RoggenLayingLogFeature;
import net.yezon.theabyss.world.features.RoggenLayingLog2Feature;
import net.yezon.theabyss.world.features.RaluFeature;
import net.yezon.theabyss.world.features.Ralu2Feature;
import net.yezon.theabyss.world.features.NightbladeAltarFeature;
import net.yezon.theabyss.world.features.MossytreeFeature;
import net.yezon.theabyss.world.features.Mossytree5Feature;
import net.yezon.theabyss.world.features.Mossytree4Feature;
import net.yezon.theabyss.world.features.Mossytree3Feature;
import net.yezon.theabyss.world.features.Mossytree2Feature;
import net.yezon.theabyss.world.features.MelonJungleFeature;
import net.yezon.theabyss.world.features.MelonJungleBlaruFeature;
import net.yezon.theabyss.world.features.LuroFeature;
import net.yezon.theabyss.world.features.Luro2Feature;
import net.yezon.theabyss.world.features.LayingTreeFeature;
import net.yezon.theabyss.world.features.LayingTree4Feature;
import net.yezon.theabyss.world.features.LayingTree3Feature;
import net.yezon.theabyss.world.features.LayingTree2Feature;
import net.yezon.theabyss.world.features.LayingSlimeFeature;
import net.yezon.theabyss.world.features.LayingLogFeature;
import net.yezon.theabyss.world.features.LaroFeature;
import net.yezon.theabyss.world.features.Laro2Feature;
import net.yezon.theabyss.world.features.JungleTreeFeature;
import net.yezon.theabyss.world.features.JungleTreeBigFeature;
import net.yezon.theabyss.world.features.JungleBushFeature;
import net.yezon.theabyss.world.features.JungleBush4Feature;
import net.yezon.theabyss.world.features.JungleBush3Feature;
import net.yezon.theabyss.world.features.JungleBush2Feature;
import net.yezon.theabyss.world.features.GiantShroomFeature;
import net.yezon.theabyss.world.features.GiantShroom2Feature;
import net.yezon.theabyss.world.features.FrozenTreeFeature;
import net.yezon.theabyss.world.features.FrozenTree2Feature;
import net.yezon.theabyss.world.features.FrostPortalFeature;
import net.yezon.theabyss.world.features.EcholotSmallFeature;
import net.yezon.theabyss.world.features.EcholotGroupFeature;
import net.yezon.theabyss.world.features.EcholotBigFeature;
import net.yezon.theabyss.world.features.DeadPhantomTreeFeature;
import net.yezon.theabyss.world.features.DeadFrozenTreeFeature;
import net.yezon.theabyss.world.features.DeadFrozenTree2Feature;
import net.yezon.theabyss.world.features.BogShroomFeature;
import net.yezon.theabyss.world.features.BogShroom2Feature;
import net.yezon.theabyss.world.features.BogMiniIsland2Feature;
import net.yezon.theabyss.world.features.BogMiniIsland1Feature;
import net.yezon.theabyss.world.features.BogIsland3Feature;
import net.yezon.theabyss.world.features.BogIsland1Feature;
import net.yezon.theabyss.world.features.BogIsland12Feature;
import net.yezon.theabyss.world.features.BlueForestBigTreeFeature;
import net.yezon.theabyss.world.features.BlaruTreeSmallFeature;
import net.yezon.theabyss.world.features.BlaruTreeSmall3Feature;
import net.yezon.theabyss.world.features.BlaruTreeSmall2Feature;
import net.yezon.theabyss.world.features.BlaruTreeMiddleFeature;
import net.yezon.theabyss.world.features.BlaruTreeMiddle3Feature;
import net.yezon.theabyss.world.features.BlaruTreeMiddle2Feature;
import net.yezon.theabyss.TheabyssMod;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.fml.common.Mod;

import net.minecraft.world.level.levelgen.feature.Feature;

@Mod.EventBusSubscriber
public class TheabyssModFeatures {
	public static final DeferredRegister<Feature<?>> REGISTRY = DeferredRegister.create(ForgeRegistries.FEATURES, TheabyssMod.MODID);
	public static final RegistryObject<Feature<?>> FUSION_ORE = REGISTRY.register("fusion_ore", FusionOreFeature::feature);
	public static final RegistryObject<Feature<?>> LORAN_ORE = REGISTRY.register("loran_ore", LoranOreFeature::feature);
	public static final RegistryObject<Feature<?>> GARNITE_ORE = REGISTRY.register("garnite_ore", GarniteOreFeature::feature);
	public static final RegistryObject<Feature<?>> IGNISITHE_ORE = REGISTRY.register("ignisithe_ore", IgnisitheOreFeature::feature);
	public static final RegistryObject<Feature<?>> ABORANYS_ORE = REGISTRY.register("aboranys_ore", AboranysOreFeature::feature);
	public static final RegistryObject<Feature<?>> GLACERYTHE_ORE = REGISTRY.register("glacerythe_ore", GlacerytheOreFeature::feature);
	public static final RegistryObject<Feature<?>> ABERYTHE_ORE = REGISTRY.register("aberythe_ore", AberytheOreFeature::feature);
	public static final RegistryObject<Feature<?>> INCORYTHE_ORE = REGISTRY.register("incorythe_ore", IncorytheOreFeature::feature);
	public static final RegistryObject<Feature<?>> DIAMOND_VARIANT = REGISTRY.register("diamond_variant", DiamondVariantFeature::feature);
	public static final RegistryObject<Feature<?>> GOLD_VARIANT = REGISTRY.register("gold_variant", GoldVariantFeature::feature);
	public static final RegistryObject<Feature<?>> IRON_VARIANT = REGISTRY.register("iron_variant", IronVariantFeature::feature);
	public static final RegistryObject<Feature<?>> EMERALD_VARIANT = REGISTRY.register("emerald_variant", EmeraldVariantFeature::feature);
	public static final RegistryObject<Feature<?>> FLORITE_ORE = REGISTRY.register("florite_ore", FloriteOreFeature::feature);
	public static final RegistryObject<Feature<?>> ROMA_MUD_2 = REGISTRY.register("roma_mud_2", RomaMud2Feature::feature);
	public static final RegistryObject<Feature<?>> DARK_STONE = REGISTRY.register("dark_stone", DarkStoneFeature::feature);
	public static final RegistryObject<Feature<?>> ARENO = REGISTRY.register("areno", ArenoFeature::feature);
	public static final RegistryObject<Feature<?>> INFECTED_PEAT = REGISTRY.register("infected_peat", InfectedPeatFeature::feature);
	public static final RegistryObject<Feature<?>> GRAVEL = REGISTRY.register("gravel", InfectedGravelFeature::feature);
	public static final RegistryObject<Feature<?>> LORAN_FLOWER = REGISTRY.register("loran_flower", LoranFlowerFeature::feature);
	public static final RegistryObject<Feature<?>> GULOM_PLANT = REGISTRY.register("gulom_plant", GulomPlantFeature::feature);
	public static final RegistryObject<Feature<?>> RALOM_PLANT = REGISTRY.register("ralom_plant", RalomPlantFeature::feature);
	public static final RegistryObject<Feature<?>> FORTIS_ULTIMA = REGISTRY.register("fortis_ultima", FortisUltimaFeature::feature);
	public static final RegistryObject<Feature<?>> OPIA_SHROOM = REGISTRY.register("opia_shroom", OpiaShroomFeature::feature);
	public static final RegistryObject<Feature<?>> THUNDER_FLOWER = REGISTRY.register("thunder_flower", ThunderFlowerFeature::feature);
	public static final RegistryObject<Feature<?>> LERCAS_UMBRELLA = REGISTRY.register("lercas_umbrella", LercasUmbrellaFeature::feature);
	public static final RegistryObject<Feature<?>> SRALA_SHROOM = REGISTRY.register("srala_shroom", SralaShroomFeature::feature);
	public static final RegistryObject<Feature<?>> SATURNIA_VERSA = REGISTRY.register("saturnia_versa", SaturniaVersaFeature::feature);
	public static final RegistryObject<Feature<?>> LUMUS_MAXIMUS = REGISTRY.register("lumus_maximus", LumusMaximusFeature::feature);
	public static final RegistryObject<Feature<?>> VERA_LESUS = REGISTRY.register("vera_lesus", VeraLesusFeature::feature);
	public static final RegistryObject<Feature<?>> OCTAVYS_MAGYNISIUS = REGISTRY.register("octavys_magynisius", OctavysMagynisiusFeature::feature);
	public static final RegistryObject<Feature<?>> CAECUS_VERSA = REGISTRY.register("caecus_versa", CaecusVersaFeature::feature);
	public static final RegistryObject<Feature<?>> FLOS_VITAE = REGISTRY.register("flos_vitae", FlosVitaeFeature::feature);
	public static final RegistryObject<Feature<?>> LERA_EXILIARIS = REGISTRY.register("lera_exiliaris", LeraExiliarisFeature::feature);
	public static final RegistryObject<Feature<?>> IGNETARIS_VERSA = REGISTRY.register("ignetaris_versa", IgnetarisVersaFeature::feature);
	public static final RegistryObject<Feature<?>> GORALYS_LASUS = REGISTRY.register("goralys_lasus", GoralysLasusFeature::feature);
	public static final RegistryObject<Feature<?>> WART_ROOT = REGISTRY.register("wart_root", WartRootFeature::feature);
	public static final RegistryObject<Feature<?>> LORAN_BUSH_2 = REGISTRY.register("loran_bush_2", LoranBush2Feature::feature);
	public static final RegistryObject<Feature<?>> LORAN_BUSH = REGISTRY.register("loran_bush", LoranBushFeature::feature);
	public static final RegistryObject<Feature<?>> TENUEM_FIRE = REGISTRY.register("tenuem_fire", TenuemFireFeature::feature);
	public static final RegistryObject<Feature<?>> ANIMA_FIRE = REGISTRY.register("anima_fire", AnimaFireFeature::feature);
	public static final RegistryObject<Feature<?>> SLIMED_VITAE = REGISTRY.register("slimed_vitae", SlimedVitaeFeature::feature);
	public static final RegistryObject<Feature<?>> ICE_RANK = REGISTRY.register("ice_rank", IceRankFeature::feature);
	public static final RegistryObject<Feature<?>> ICORA_FLOWER = REGISTRY.register("icora_flower", IcoraFlowerFeature::feature);
	public static final RegistryObject<Feature<?>> TESLA_RANK = REGISTRY.register("tesla_rank", TeslaRankFeature::feature);
	public static final RegistryObject<Feature<?>> ICELA_RANK = REGISTRY.register("icela_rank", IcelaRankFeature::feature);
	public static final RegistryObject<Feature<?>> ROTTEN_RANK = REGISTRY.register("rotten_rank", RottenRankFeature::feature);
	public static final RegistryObject<Feature<?>> GRASS_SMALL = REGISTRY.register("grass_small", GrassSmallFeature::feature);
	public static final RegistryObject<Feature<?>> GRASS_MIDDLE = REGISTRY.register("grass_middle", GrassMiddleFeature::feature);
	public static final RegistryObject<Feature<?>> GRASS_BIG = REGISTRY.register("grass_big", GrassBigFeature::feature);
	public static final RegistryObject<Feature<?>> TALL_GLOW_SHROOM = REGISTRY.register("tall_glow_shroom", TallGlowShroomFeature::feature);
	public static final RegistryObject<Feature<?>> GLOW_SHROOM = REGISTRY.register("glow_shroom", GlowShroomFeature::feature);
	public static final RegistryObject<Feature<?>> TALL_RUB_SHROOM = REGISTRY.register("tall_rub_shroom", TallRubShroomFeature::feature);
	public static final RegistryObject<Feature<?>> RUB_SHROOM = REGISTRY.register("rub_shroom", RubShroomFeature::feature);
	public static final RegistryObject<Feature<?>> VERTA_CELSIUS = REGISTRY.register("verta_celsius", VertaCelsiusFeature::feature);
	public static final RegistryObject<Feature<?>> MINI_STONE_1 = REGISTRY.register("mini_stone_1", MiniStone1Feature::feature);
	public static final RegistryObject<Feature<?>> TANTRA_GRASS_SMALL = REGISTRY.register("tantra_grass_small", TantraGrassSmallFeature::feature);
	public static final RegistryObject<Feature<?>> TANTRA_GRASS_MIDDLE = REGISTRY.register("tantra_grass_middle", TantraGrassMiddleFeature::feature);
	public static final RegistryObject<Feature<?>> TANTRA_GRASS_BIG = REGISTRY.register("tantra_grass_big", TantraGrassBigFeature::feature);
	public static final RegistryObject<Feature<?>> LAZARUS_GRASS = REGISTRY.register("lazarus_grass", LazarusGrassFeature::feature);
	public static final RegistryObject<Feature<?>> LUMUS_GRASS = REGISTRY.register("lumus_grass", LumusGrassFeature::feature);
	public static final RegistryObject<Feature<?>> LUMUS_FLOWER = REGISTRY.register("lumus_flower", LumusFlowerFeature::feature);
	public static final RegistryObject<Feature<?>> VEALUS_MERAMUS = REGISTRY.register("vealus_meramus", VealusMeramusFeature::feature);
	public static final RegistryObject<Feature<?>> CRIMSON_CRYSTAL_ORE = REGISTRY.register("crimson_crystal_ore", CrimsonCrystalOreFeature::feature);
	public static final RegistryObject<Feature<?>> WARPED_CRYSTAL_ORE = REGISTRY.register("warped_crystal_ore", WarpedCrystalOreFeature::feature);
	public static final RegistryObject<Feature<?>> AUREL_CRYSTAL_ORE = REGISTRY.register("aurel_crystal_ore", AurelCrystalOreFeature::feature);
	public static final RegistryObject<Feature<?>> CAVERNA_CRYSTAL_ORE = REGISTRY.register("caverna_crystal_ore", CavernaCrystalOreFeature::feature);
	public static final RegistryObject<Feature<?>> ENDER_CRYSTAL_ORE = REGISTRY.register("ender_crystal_ore", EnderCrystalOreFeature::feature);
	public static final RegistryObject<Feature<?>> FROST_CRYSTAL_ORE = REGISTRY.register("frost_crystal_ore", FrostCrystalOreFeature::feature);
	public static final RegistryObject<Feature<?>> ABYSS_CRYSTAL_ORE = REGISTRY.register("abyss_crystal_ore", AbyssCrystalOreFeature::feature);
	public static final RegistryObject<Feature<?>> HOLLOW_CRYSTAL_ORE = REGISTRY.register("hollow_crystal_ore", HollowCrystalOreFeature::feature);
	public static final RegistryObject<Feature<?>> EXOLIUS_PLANT = REGISTRY.register("exolius_plant", ExoliusPlantFeature::feature);
	public static final RegistryObject<Feature<?>> YOUNG_EXOLIUS_PLANT = REGISTRY.register("young_exolius_plant", YoungExoliusPlantFeature::feature);
	public static final RegistryObject<Feature<?>> BLARU_LEAVE_CARPET = REGISTRY.register("blaru_leave_carpet", BlaruLeaveCarpetFeature::feature);
	public static final RegistryObject<Feature<?>> JUNGLE_LEAVE_CARPET = REGISTRY.register("jungle_leave_carpet", JungleLeaveCarpetFeature::feature);
	public static final RegistryObject<Feature<?>> SLIMED_CARPET = REGISTRY.register("slimed_carpet", SlimedCarpetFeature::feature);
	public static final RegistryObject<Feature<?>> LUNGO_RANK = REGISTRY.register("lungo_rank", LungoRankFeature::feature);
	public static final RegistryObject<Feature<?>> GLOWING_BLARU_MOSS = REGISTRY.register("glowing_blaru_moss", GlowingBlaruMossFeature::feature);
	public static final RegistryObject<Feature<?>> AUREL_CAVE_MOSS = REGISTRY.register("aurel_cave_moss", AurelCaveMossFeature::feature);
	public static final RegistryObject<Feature<?>> AUREL_SHROOM = REGISTRY.register("aurel_shroom", AurelShroomFeature::feature);
	public static final RegistryObject<Feature<?>> AUREL_LEAVE_CARPET = REGISTRY.register("aurel_leave_carpet", AurelLeaveCarpetFeature::feature);
	public static final RegistryObject<Feature<?>> AUREL_RANK = REGISTRY.register("aurel_rank", AurelRankFeature::feature);
	public static final RegistryObject<Feature<?>> BLARU_CAVE_MOSS = REGISTRY.register("blaru_cave_moss", BlaruCaveMossFeature::feature);
	public static final RegistryObject<Feature<?>> JUNGLE_TREE = REGISTRY.register("jungle_tree", JungleTreeFeature::feature);
	public static final RegistryObject<Feature<?>> JUNGLE_TREE_BIG = REGISTRY.register("jungle_tree_big", JungleTreeBigFeature::feature);
	public static final RegistryObject<Feature<?>> JUNGLE_BUSH = REGISTRY.register("jungle_bush", JungleBushFeature::feature);
	public static final RegistryObject<Feature<?>> JUNGLE_BUSH_2 = REGISTRY.register("jungle_bush_2", JungleBush2Feature::feature);
	public static final RegistryObject<Feature<?>> JUNGLE_BUSH_3 = REGISTRY.register("jungle_bush_3", JungleBush3Feature::feature);
	public static final RegistryObject<Feature<?>> LAYING_TREE = REGISTRY.register("laying_tree", LayingTreeFeature::feature);
	public static final RegistryObject<Feature<?>> LAYING_TREE_2 = REGISTRY.register("laying_tree_2", LayingTree2Feature::feature);
	public static final RegistryObject<Feature<?>> LAYING_TREE_3 = REGISTRY.register("laying_tree_3", LayingTree3Feature::feature);
	public static final RegistryObject<Feature<?>> LAYING_TREE_4 = REGISTRY.register("laying_tree_4", LayingTree4Feature::feature);
	public static final RegistryObject<Feature<?>> JUNGLE_BUSH_4 = REGISTRY.register("jungle_bush_4", JungleBush4Feature::feature);
	public static final RegistryObject<Feature<?>> NIGHTBLADE_ALTAR = REGISTRY.register("nightblade_altar", NightbladeAltarFeature::feature);
	public static final RegistryObject<Feature<?>> ECHOLOT_GROUP = REGISTRY.register("echolot_group", EcholotGroupFeature::feature);
	public static final RegistryObject<Feature<?>> ECHOLOT_SMALL = REGISTRY.register("echolot_small", EcholotSmallFeature::feature);
	public static final RegistryObject<Feature<?>> ECHOLOT_BIG = REGISTRY.register("echolot_big", EcholotBigFeature::feature);
	public static final RegistryObject<Feature<?>> GIANT_SHROOM = REGISTRY.register("giant_shroom", GiantShroomFeature::feature);
	public static final RegistryObject<Feature<?>> GIANT_SHROOM_2 = REGISTRY.register("giant_shroom_2", GiantShroom2Feature::feature);
	public static final RegistryObject<Feature<?>> LUMA_GRASS = REGISTRY.register("luma_grass", LumaGrassFeature::feature);
	public static final RegistryObject<Feature<?>> ROGGEN_TREE = REGISTRY.register("roggen_tree", RoggenTreeFeature::feature);
	public static final RegistryObject<Feature<?>> ROGGEN_TREE_2 = REGISTRY.register("roggen_tree_2", RoggenTree2Feature::feature);
	public static final RegistryObject<Feature<?>> ROGGEN_TREE_3 = REGISTRY.register("roggen_tree_3", RoggenTree3Feature::feature);
	public static final RegistryObject<Feature<?>> ROGGEN_LAYING_LOG = REGISTRY.register("roggen_laying_log", RoggenLayingLogFeature::feature);
	public static final RegistryObject<Feature<?>> ROGGEN_LAYING_LOG_2 = REGISTRY.register("roggen_laying_log_2", RoggenLayingLog2Feature::feature);
	public static final RegistryObject<Feature<?>> RUMA_LAYING_LOG = REGISTRY.register("ruma_laying_log", RumaLayingLogFeature::feature);
	public static final RegistryObject<Feature<?>> RUMA_LAYING_LOG_2 = REGISTRY.register("ruma_laying_log_2", RumaLayingLog2Feature::feature);
	public static final RegistryObject<Feature<?>> RUMA_LAYING_LOG_3 = REGISTRY.register("ruma_laying_log_3", RumaLayingLog3Feature::feature);
	public static final RegistryObject<Feature<?>> BLARU_TREE_MIDDLE = REGISTRY.register("blaru_tree_middle", BlaruTreeMiddleFeature::feature);
	public static final RegistryObject<Feature<?>> ROTTEN_GIANT_SHROOM = REGISTRY.register("rotten_giant_shroom", RottenGiantShroomFeature::feature);
	public static final RegistryObject<Feature<?>> TANTRA_TREE = REGISTRY.register("tantra_tree", TantraTreeFeature::feature);
	public static final RegistryObject<Feature<?>> TANTRA_TREE_RUMA = REGISTRY.register("tantra_tree_ruma", TantraTreeRumaFeature::feature);
	public static final RegistryObject<Feature<?>> MELON_JUNGLE = REGISTRY.register("melon_jungle", MelonJungleFeature::feature);
	public static final RegistryObject<Feature<?>> BOG_SHROOM = REGISTRY.register("bog_shroom", BogShroomFeature::feature);
	public static final RegistryObject<Feature<?>> SAL_SHROOM = REGISTRY.register("sal_shroom", SalShroomFeature::feature);
	public static final RegistryObject<Feature<?>> DEAD_PHANTOM_TREE = REGISTRY.register("dead_phantom_tree", DeadPhantomTreeFeature::feature);
	public static final RegistryObject<Feature<?>> MOSSYTREE = REGISTRY.register("mossytree", MossytreeFeature::feature);
	public static final RegistryObject<Feature<?>> MOSSYTREE_2 = REGISTRY.register("mossytree_2", Mossytree2Feature::feature);
	public static final RegistryObject<Feature<?>> MOSSYTREE_3 = REGISTRY.register("mossytree_3", Mossytree3Feature::feature);
	public static final RegistryObject<Feature<?>> RALU = REGISTRY.register("ralu", RaluFeature::feature);
	public static final RegistryObject<Feature<?>> LURO = REGISTRY.register("luro", LuroFeature::feature);
	public static final RegistryObject<Feature<?>> LARO = REGISTRY.register("laro", LaroFeature::feature);
	public static final RegistryObject<Feature<?>> SLIME_TREE = REGISTRY.register("slime_tree", SlimeTreeFeature::feature);
	public static final RegistryObject<Feature<?>> SLIMED_GIANT_SHROOM = REGISTRY.register("slimed_giant_shroom", SlimedGiantShroomFeature::feature);
	public static final RegistryObject<Feature<?>> LAYING_LOG = REGISTRY.register("laying_log", LayingLogFeature::feature);
	public static final RegistryObject<Feature<?>> LAYING_SLIME = REGISTRY.register("laying_slime", LayingSlimeFeature::feature);
	public static final RegistryObject<Feature<?>> SLIMED_CRATER = REGISTRY.register("slimed_crater", SlimedCraterFeature::feature);
	public static final RegistryObject<Feature<?>> SLIME_CRATER_2 = REGISTRY.register("slime_crater_2", SlimeCrater2Feature::feature);
	public static final RegistryObject<Feature<?>> SKEL_BONE = REGISTRY.register("skel_bone", SkelBoneFeature::feature);
	public static final RegistryObject<Feature<?>> FROZEN_TREE = REGISTRY.register("frozen_tree", FrozenTreeFeature::feature);
	public static final RegistryObject<Feature<?>> DEAD_FROZEN_TREE = REGISTRY.register("dead_frozen_tree", DeadFrozenTreeFeature::feature);
	public static final RegistryObject<Feature<?>> DEAD_FROZEN_TREE_2 = REGISTRY.register("dead_frozen_tree_2", DeadFrozenTree2Feature::feature);
	public static final RegistryObject<Feature<?>> FROZEN_TREE_2 = REGISTRY.register("frozen_tree_2", FrozenTree2Feature::feature);
	public static final RegistryObject<Feature<?>> RALU_2 = REGISTRY.register("ralu_2", Ralu2Feature::feature);
	public static final RegistryObject<Feature<?>> LURO_2 = REGISTRY.register("luro_2", Luro2Feature::feature);
	public static final RegistryObject<Feature<?>> LARO_2 = REGISTRY.register("laro_2", Laro2Feature::feature);
	public static final RegistryObject<Feature<?>> BLARU_TREE_MIDDLE_2 = REGISTRY.register("blaru_tree_middle_2", BlaruTreeMiddle2Feature::feature);
	public static final RegistryObject<Feature<?>> BLARU_TREE_SMALL = REGISTRY.register("blaru_tree_small", BlaruTreeSmallFeature::feature);
	public static final RegistryObject<Feature<?>> BLARU_TREE_SMALL_2 = REGISTRY.register("blaru_tree_small_2", BlaruTreeSmall2Feature::feature);
	public static final RegistryObject<Feature<?>> BLARU_TREE_MIDDLE_3 = REGISTRY.register("blaru_tree_middle_3", BlaruTreeMiddle3Feature::feature);
	public static final RegistryObject<Feature<?>> MELON_JUNGLE_BLARU = REGISTRY.register("melon_jungle_blaru", MelonJungleBlaruFeature::feature);
	public static final RegistryObject<Feature<?>> BLARU_TREE_SMALL_3 = REGISTRY.register("blaru_tree_small_3", BlaruTreeSmall3Feature::feature);
	public static final RegistryObject<Feature<?>> BLUE_FOREST_BIG_TREE = REGISTRY.register("blue_forest_big_tree",
			BlueForestBigTreeFeature::feature);
	public static final RegistryObject<Feature<?>> RAPTOR_EGG = REGISTRY.register("raptor_egg", RaptorEggFeature::feature);
	public static final RegistryObject<Feature<?>> WATER_ECHOLOT_GROUP_MIDDLE = REGISTRY.register("water_echolot_group_middle",
			WaterEcholotGroupMiddleFeature::feature);
	public static final RegistryObject<Feature<?>> ROTTEN_TREE = REGISTRY.register("rotten_tree", RottenTreeFeature::feature);
	public static final RegistryObject<Feature<?>> ROTTEN_TREE_2 = REGISTRY.register("rotten_tree_2", RottenTree2Feature::feature);
	public static final RegistryObject<Feature<?>> WART_RANK_BIG = REGISTRY.register("wart_rank_big", WartRankBigFeature::feature);
	public static final RegistryObject<Feature<?>> WART_RANK_SMALL = REGISTRY.register("wart_rank_small", WartRankSmallFeature::feature);
	public static final RegistryObject<Feature<?>> MOSSYTREE_4 = REGISTRY.register("mossytree_4", Mossytree4Feature::feature);
	public static final RegistryObject<Feature<?>> MOSSYTREE_5 = REGISTRY.register("mossytree_5", Mossytree5Feature::feature);
	public static final RegistryObject<Feature<?>> BOG_ISLAND_1 = REGISTRY.register("bog_island_1", BogIsland1Feature::feature);
	public static final RegistryObject<Feature<?>> BOG_ISLAND_12 = REGISTRY.register("bog_island_12", BogIsland12Feature::feature);
	public static final RegistryObject<Feature<?>> BOG_ISLAND_3 = REGISTRY.register("bog_island_3", BogIsland3Feature::feature);
	public static final RegistryObject<Feature<?>> BOG_MINI_ISLAND_1 = REGISTRY.register("bog_mini_island_1", BogMiniIsland1Feature::feature);
	public static final RegistryObject<Feature<?>> BOG_MINI_ISLAND_2 = REGISTRY.register("bog_mini_island_2", BogMiniIsland2Feature::feature);
	public static final RegistryObject<Feature<?>> BOG_SHROOM_2 = REGISTRY.register("bog_shroom_2", BogShroom2Feature::feature);
	public static final RegistryObject<Feature<?>> FROST_PORTAL = REGISTRY.register("frost_portal", FrostPortalFeature::feature);
	public static final RegistryObject<Feature<?>> SLIMED_TENTACLE = REGISTRY.register("slimed_tentacle", SlimedTentacleFeature::feature);
	public static final RegistryObject<Feature<?>> SLIMED_RANK_1 = REGISTRY.register("slimed_rank_1", SlimedRank1Feature::feature);
	public static final RegistryObject<Feature<?>> SLIMED_RANK_2 = REGISTRY.register("slimed_rank_2", SlimedRank2Feature::feature);
	public static final RegistryObject<Feature<?>> SLIMED_RANK_3 = REGISTRY.register("slimed_rank_3", SlimedRank3Feature::feature);
}
