
/*
 *    Y3 was here UwU ^-^
 */
package net.yezon.theabyss.init;

import net.yezon.theabyss.block.YoungExoliusPlantBlock;
import net.yezon.theabyss.block.WaterEcholotTopBlock;
import net.yezon.theabyss.block.WaterEcholotMiddleBlock;
import net.yezon.theabyss.block.WaterEcholotBottomBlock;
import net.yezon.theabyss.block.WartRootBlock;
import net.yezon.theabyss.block.WartRankEndBlock;
import net.yezon.theabyss.block.WartRankBlock;
import net.yezon.theabyss.block.WartBlock;
import net.yezon.theabyss.block.WarpedCrystalOreBlock;
import net.yezon.theabyss.block.VertaCelsiusBlock;
import net.yezon.theabyss.block.VeraLesusBlock;
import net.yezon.theabyss.block.VealusMeramusBlock;
import net.yezon.theabyss.block.UnstableObsidianBlock;
import net.yezon.theabyss.block.ThunderFlowerBlock;
import net.yezon.theabyss.block.TheabyssdimiceworldPortalBlock;
import net.yezon.theabyss.block.TheAbyssDimPortalBlock;
import net.yezon.theabyss.block.TheAbyssDimGroundlandsPortalBlock;
import net.yezon.theabyss.block.TeslaRankBlock;
import net.yezon.theabyss.block.TenuemFireBlock;
import net.yezon.theabyss.block.TantraVineBlock;
import net.yezon.theabyss.block.TantraTrapDoorBlock;
import net.yezon.theabyss.block.TantraTableBlock;
import net.yezon.theabyss.block.TantraStoneBlock;
import net.yezon.theabyss.block.TantraStairsBlock;
import net.yezon.theabyss.block.TantraSlabBlock;
import net.yezon.theabyss.block.TantraPressurePlateBlock;
import net.yezon.theabyss.block.TantraPlanksBlock;
import net.yezon.theabyss.block.TantraLogBlock;
import net.yezon.theabyss.block.TantraLeavesBlock;
import net.yezon.theabyss.block.TantraLadderBlock;
import net.yezon.theabyss.block.TantraGrassSmallBlock;
import net.yezon.theabyss.block.TantraGrassMiddleBlock;
import net.yezon.theabyss.block.TantraGrassBlock;
import net.yezon.theabyss.block.TantraGrassBigBlock;
import net.yezon.theabyss.block.TantraFenceGateBlock;
import net.yezon.theabyss.block.TantraFenceBlock;
import net.yezon.theabyss.block.TantraDoorBlock;
import net.yezon.theabyss.block.TantraDirtBlock;
import net.yezon.theabyss.block.TantraCobblestoneBlock;
import net.yezon.theabyss.block.TantraChairBlock;
import net.yezon.theabyss.block.TantraButtonBlock;
import net.yezon.theabyss.block.TallRubShroomBlock;
import net.yezon.theabyss.block.TallGlowShroomBlock;
import net.yezon.theabyss.block.StrippedTantraLogBlock;
import net.yezon.theabyss.block.StrippedRumaLogBlock;
import net.yezon.theabyss.block.StrippedRoggenLogBlock;
import net.yezon.theabyss.block.StrippedBlaruLogBlock;
import net.yezon.theabyss.block.StoneStairsBlock;
import net.yezon.theabyss.block.StoneSlabsBlock;
import net.yezon.theabyss.block.StoneBrickWallBlock;
import net.yezon.theabyss.block.StoneBrickStairsBlock;
import net.yezon.theabyss.block.StoneBrickSlabBlock;
import net.yezon.theabyss.block.StoneBrickPillarIgnitedBlock;
import net.yezon.theabyss.block.StoneBrickPillarBlock;
import net.yezon.theabyss.block.StoneBrickChiseledBlock;
import net.yezon.theabyss.block.StoneBrickBrokenBlock;
import net.yezon.theabyss.block.StoneBrickBlock;
import net.yezon.theabyss.block.StoneBlock;
import net.yezon.theabyss.block.StippedJungleLogBlock;
import net.yezon.theabyss.block.SralaShroomBlock;
import net.yezon.theabyss.block.SomniumInfuserBlock;
import net.yezon.theabyss.block.SomniumExtractorBlock;
import net.yezon.theabyss.block.SnowBlockBlock;
import net.yezon.theabyss.block.SlimedVitaeBlock;
import net.yezon.theabyss.block.SlimedTrapDoorBlock;
import net.yezon.theabyss.block.SlimedTableBlock;
import net.yezon.theabyss.block.SlimedStairsBlock;
import net.yezon.theabyss.block.SlimedSlabBlock;
import net.yezon.theabyss.block.SlimedRankBlock;
import net.yezon.theabyss.block.SlimedPressurePlateBlock;
import net.yezon.theabyss.block.SlimedPlanksBlock;
import net.yezon.theabyss.block.SlimedLogVineBlock;
import net.yezon.theabyss.block.SlimedLogFungiBlock;
import net.yezon.theabyss.block.SlimedLogCrystalBlock;
import net.yezon.theabyss.block.SlimedLogBlock;
import net.yezon.theabyss.block.SlimedLadderBlock;
import net.yezon.theabyss.block.SlimedFenceGateBlock;
import net.yezon.theabyss.block.SlimedFenceBlock;
import net.yezon.theabyss.block.SlimedDoorBlock;
import net.yezon.theabyss.block.SlimedChairBlock;
import net.yezon.theabyss.block.SlimedCarpetBlock;
import net.yezon.theabyss.block.SlimedButtonBlock;
import net.yezon.theabyss.block.SlimeRootBlockBlock;
import net.yezon.theabyss.block.SlimeBlockBlock;
import net.yezon.theabyss.block.ShieldCampFireBlock;
import net.yezon.theabyss.block.SaturniaVersaBlock;
import net.yezon.theabyss.block.SalVineBlock;
import net.yezon.theabyss.block.SalTrapDoorBlock;
import net.yezon.theabyss.block.SalTableBlock;
import net.yezon.theabyss.block.SalStairsBlock;
import net.yezon.theabyss.block.SalSlabBlock;
import net.yezon.theabyss.block.SalShroomLogBlock;
import net.yezon.theabyss.block.SalShroomLeaveBlock;
import net.yezon.theabyss.block.SalPressurePlateBlock;
import net.yezon.theabyss.block.SalPlanksBlock;
import net.yezon.theabyss.block.SalLogFungiBlock;
import net.yezon.theabyss.block.SalLadderBlock;
import net.yezon.theabyss.block.SalFenceGateBlock;
import net.yezon.theabyss.block.SalFenceBlock;
import net.yezon.theabyss.block.SalDoorBlock;
import net.yezon.theabyss.block.SalChairBlock;
import net.yezon.theabyss.block.SalButtonBlock;
import net.yezon.theabyss.block.RumaTrapDoorBlock;
import net.yezon.theabyss.block.RumaTableBlock;
import net.yezon.theabyss.block.RumaStairsBlock;
import net.yezon.theabyss.block.RumaSlabBlock;
import net.yezon.theabyss.block.RumaPressurePlateBlock;
import net.yezon.theabyss.block.RumaPlanksBlock;
import net.yezon.theabyss.block.RumaLogVineBlock;
import net.yezon.theabyss.block.RumaLogFungiBlock;
import net.yezon.theabyss.block.RumaLogFungi2Block;
import net.yezon.theabyss.block.RumaLogBlock;
import net.yezon.theabyss.block.RumaLeaveBlock;
import net.yezon.theabyss.block.RumaLeave5Block;
import net.yezon.theabyss.block.RumaLeave4Block;
import net.yezon.theabyss.block.RumaLeave3Block;
import net.yezon.theabyss.block.RumaLeave2Block;
import net.yezon.theabyss.block.RumaLadderBlock;
import net.yezon.theabyss.block.RumaFenceGateBlock;
import net.yezon.theabyss.block.RumaFenceBlock;
import net.yezon.theabyss.block.RumaDoorBlock;
import net.yezon.theabyss.block.RumaChairBlock;
import net.yezon.theabyss.block.RumaButtonBlock;
import net.yezon.theabyss.block.RumaBookshelfBlock;
import net.yezon.theabyss.block.RubShroomBlock;
import net.yezon.theabyss.block.RottenRankBlock;
import net.yezon.theabyss.block.RottenLogVineBlock;
import net.yezon.theabyss.block.RottenLogBlock;
import net.yezon.theabyss.block.RottenLeaveBlock;
import net.yezon.theabyss.block.RottenFungalLeaveBlock;
import net.yezon.theabyss.block.RomaMudBlock;
import net.yezon.theabyss.block.RomaMud2Block;
import net.yezon.theabyss.block.RoggenVineBlock;
import net.yezon.theabyss.block.RoggenTrapDoorBlock;
import net.yezon.theabyss.block.RoggenTableBlock;
import net.yezon.theabyss.block.RoggenStairsBlock;
import net.yezon.theabyss.block.RoggenSlabBlock;
import net.yezon.theabyss.block.RoggenPressurePlateBlock;
import net.yezon.theabyss.block.RoggenPlanksBlock;
import net.yezon.theabyss.block.RoggenLogBlock;
import net.yezon.theabyss.block.RoggenLeaveBlock;
import net.yezon.theabyss.block.RoggenLadderBlock;
import net.yezon.theabyss.block.RoggenFenceGateBlock;
import net.yezon.theabyss.block.RoggenFenceBlock;
import net.yezon.theabyss.block.RoggenDoorBlock;
import net.yezon.theabyss.block.RoggenChairBlock;
import net.yezon.theabyss.block.RoggenButtonBlock;
import net.yezon.theabyss.block.ResearchTableBlock;
import net.yezon.theabyss.block.RaptorEggBlock;
import net.yezon.theabyss.block.RalomPlantBlock;
import net.yezon.theabyss.block.PurpleShroomlightBlock;
import net.yezon.theabyss.block.PhantomLanternBlock;
import net.yezon.theabyss.block.PhantomHangingLanternBlock;
import net.yezon.theabyss.block.OpiaShroomBlock;
import net.yezon.theabyss.block.OctavysMagynisiusBlock;
import net.yezon.theabyss.block.NightAltarBlock;
import net.yezon.theabyss.block.NightAltarActivatedBlock;
import net.yezon.theabyss.block.MortarAndPestleBlock;
import net.yezon.theabyss.block.MiniStone1Block;
import net.yezon.theabyss.block.LungoRankBlock;
import net.yezon.theabyss.block.LumusRankBlock;
import net.yezon.theabyss.block.LumusMaximusBlock;
import net.yezon.theabyss.block.LumusGrassBlock;
import net.yezon.theabyss.block.LumusFruitBlock;
import net.yezon.theabyss.block.LumusFlowerBlock;
import net.yezon.theabyss.block.LumaGrassBlock;
import net.yezon.theabyss.block.LorkaVineBlock;
import net.yezon.theabyss.block.LorkaLeavesBlock;
import net.yezon.theabyss.block.LoranOreBlock;
import net.yezon.theabyss.block.LoranFlowerBlock;
import net.yezon.theabyss.block.LoranBushBlock;
import net.yezon.theabyss.block.LoranBush2Block;
import net.yezon.theabyss.block.LercasUmbrellaBlock;
import net.yezon.theabyss.block.LeraExiliarisBlock;
import net.yezon.theabyss.block.LazarusGrassBlock;
import net.yezon.theabyss.block.JungleVineBlock;
import net.yezon.theabyss.block.JungleTrapDoorBlock;
import net.yezon.theabyss.block.JungleTableBlock;
import net.yezon.theabyss.block.JungleStairsBlock;
import net.yezon.theabyss.block.JungleSlabBlock;
import net.yezon.theabyss.block.JunglePressurePlateBlock;
import net.yezon.theabyss.block.JunglePlanksBlock;
import net.yezon.theabyss.block.JungleMelonBlock;
import net.yezon.theabyss.block.JungleLogVineBlock;
import net.yezon.theabyss.block.JungleLogFungiBlock;
import net.yezon.theabyss.block.JungleLogBlock;
import net.yezon.theabyss.block.JungleLeavesBlock;
import net.yezon.theabyss.block.JungleLeaveCarpetBlock;
import net.yezon.theabyss.block.JungleLadderBlock;
import net.yezon.theabyss.block.JungleFenceGateBlock;
import net.yezon.theabyss.block.JungleFenceBlock;
import net.yezon.theabyss.block.JungleDoorBlock;
import net.yezon.theabyss.block.JungleChairBlock;
import net.yezon.theabyss.block.JungleButtonBlock;
import net.yezon.theabyss.block.JungleBookshelfBlock;
import net.yezon.theabyss.block.IronVariantBlock;
import net.yezon.theabyss.block.InfusedMagmaBlock;
import net.yezon.theabyss.block.InfectedPeatBlock;
import net.yezon.theabyss.block.InfectedGravelBlock;
import net.yezon.theabyss.block.InfectedGrassBlock;
import net.yezon.theabyss.block.IncorytheOreBlock;
import net.yezon.theabyss.block.IgnisitheOreBlock;
import net.yezon.theabyss.block.IgnetarisVersaBlock;
import net.yezon.theabyss.block.IcoraFlowerBlock;
import net.yezon.theabyss.block.IcelaRankBlock;
import net.yezon.theabyss.block.IceRankBlock;
import net.yezon.theabyss.block.HollowCrystalOreBlock;
import net.yezon.theabyss.block.HoglinLanternBlock;
import net.yezon.theabyss.block.HoglinHangingLanternBlock;
import net.yezon.theabyss.block.HealCampFireBlock;
import net.yezon.theabyss.block.GulomPlantBlock;
import net.yezon.theabyss.block.GrassSmallBlock;
import net.yezon.theabyss.block.GrassMiddleBlock;
import net.yezon.theabyss.block.GrassBigBlock;
import net.yezon.theabyss.block.GoralysLasusBlock;
import net.yezon.theabyss.block.GoldVariantBlock;
import net.yezon.theabyss.block.GlowingBlaruMossBlock;
import net.yezon.theabyss.block.GlowShroomBlock;
import net.yezon.theabyss.block.GlacerytheOreBlock;
import net.yezon.theabyss.block.GarniteOreBlock;
import net.yezon.theabyss.block.FusionOreBlock;
import net.yezon.theabyss.block.FrozenTrapDoorBlock;
import net.yezon.theabyss.block.FrozenTableBlock;
import net.yezon.theabyss.block.FrozenStairsBlock;
import net.yezon.theabyss.block.FrozenSlabBlock;
import net.yezon.theabyss.block.FrozenPressurePlateBlock;
import net.yezon.theabyss.block.FrozenPlanksBlock;
import net.yezon.theabyss.block.FrozenLogVineBlock;
import net.yezon.theabyss.block.FrozenLogBlock;
import net.yezon.theabyss.block.FrozenLeavesBlock;
import net.yezon.theabyss.block.FrozenLadderBlock;
import net.yezon.theabyss.block.FrozenFenceGateBlock;
import net.yezon.theabyss.block.FrozenFenceBlock;
import net.yezon.theabyss.block.FrozenDoorBlock;
import net.yezon.theabyss.block.FrozenChairBlock;
import net.yezon.theabyss.block.FrozenButtonBlock;
import net.yezon.theabyss.block.FrostCrystalOreBlock;
import net.yezon.theabyss.block.FrostBricksSlabBlock;
import net.yezon.theabyss.block.FrostBrickWallBlock;
import net.yezon.theabyss.block.FrostBrickStairsBlock;
import net.yezon.theabyss.block.FrostBrickCrackedBlock;
import net.yezon.theabyss.block.FrostBrickBlock;
import net.yezon.theabyss.block.FortisUltimaBlock;
import net.yezon.theabyss.block.FlosVitaeBlock;
import net.yezon.theabyss.block.FloriteOreBlock;
import net.yezon.theabyss.block.ExoliusPlantBlock;
import net.yezon.theabyss.block.EnderLanternBlock;
import net.yezon.theabyss.block.EnderHangingLanternBlock;
import net.yezon.theabyss.block.EnderCrystalOreBlock;
import net.yezon.theabyss.block.EmeraldVariantBlock;
import net.yezon.theabyss.block.EcholotTopBlock;
import net.yezon.theabyss.block.EcholotMiddleBlock;
import net.yezon.theabyss.block.EcholotBottomBlock;
import net.yezon.theabyss.block.DirtBlock;
import net.yezon.theabyss.block.DiamondVariantBlock;
import net.yezon.theabyss.block.DarkStoneBlock;
import net.yezon.theabyss.block.DarkBlueShroomlightBlock;
import net.yezon.theabyss.block.CrystalCutterBlock;
import net.yezon.theabyss.block.CrimsonCrystalOreBlock;
import net.yezon.theabyss.block.CobbleStoneWallBlock;
import net.yezon.theabyss.block.CobbleStoneStairsBlock;
import net.yezon.theabyss.block.CobbleStoneSlabBlock;
import net.yezon.theabyss.block.CobbleStoneBlock;
import net.yezon.theabyss.block.CavernaCrystalOreBlock;
import net.yezon.theabyss.block.CaecusVersaBlock;
import net.yezon.theabyss.block.BrokenRadioBlock;
import net.yezon.theabyss.block.BoneThinBlock;
import net.yezon.theabyss.block.BoneBlock;
import net.yezon.theabyss.block.BogVineBlock;
import net.yezon.theabyss.block.BogTrapDoorBlock;
import net.yezon.theabyss.block.BogTableBlock;
import net.yezon.theabyss.block.BogStairsBlock;
import net.yezon.theabyss.block.BogSlabBlock;
import net.yezon.theabyss.block.BogShroomLogBlock;
import net.yezon.theabyss.block.BogShroomLeaveBlock;
import net.yezon.theabyss.block.BogPressurePlateBlock;
import net.yezon.theabyss.block.BogPlanksBlock;
import net.yezon.theabyss.block.BogLogFungiBlock;
import net.yezon.theabyss.block.BogLadderBlock;
import net.yezon.theabyss.block.BogFenceGateBlock;
import net.yezon.theabyss.block.BogFenceBlock;
import net.yezon.theabyss.block.BogDoorBlock;
import net.yezon.theabyss.block.BogChairBlock;
import net.yezon.theabyss.block.BogButtonBlock;
import net.yezon.theabyss.block.BlueShroomlightBlock;
import net.yezon.theabyss.block.BlaruVineBlock;
import net.yezon.theabyss.block.BlaruTrapDoorBlock;
import net.yezon.theabyss.block.BlaruTableBlock;
import net.yezon.theabyss.block.BlaruStairsBlock;
import net.yezon.theabyss.block.BlaruSlabBlock;
import net.yezon.theabyss.block.BlaruPressurePlateBlock;
import net.yezon.theabyss.block.BlaruPlanksBlock;
import net.yezon.theabyss.block.BlaruMossBlock;
import net.yezon.theabyss.block.BlaruLogVineBlock;
import net.yezon.theabyss.block.BlaruLogFungiBlock;
import net.yezon.theabyss.block.BlaruLogBlock;
import net.yezon.theabyss.block.BlaruLeavesBlock;
import net.yezon.theabyss.block.BlaruLeaveCarpetBlock;
import net.yezon.theabyss.block.BlaruLadderBlock;
import net.yezon.theabyss.block.BlaruFenceGateBlock;
import net.yezon.theabyss.block.BlaruFenceBlock;
import net.yezon.theabyss.block.BlaruDoorBlock;
import net.yezon.theabyss.block.BlaruChairBlock;
import net.yezon.theabyss.block.BlaruCaveMossBlock;
import net.yezon.theabyss.block.BlaruButtonBlock;
import net.yezon.theabyss.block.BlaruBookshelfBlock;
import net.yezon.theabyss.block.BlackVoidBlock;
import net.yezon.theabyss.block.AurelShroomBlock;
import net.yezon.theabyss.block.AurelRankBlock;
import net.yezon.theabyss.block.AurelLeaveCarpetBlock;
import net.yezon.theabyss.block.AurelCrystalOreBlock;
import net.yezon.theabyss.block.AurelCaveMossBlock;
import net.yezon.theabyss.block.ArenoBlock;
import net.yezon.theabyss.block.ArcaneWorkbenchBlock;
import net.yezon.theabyss.block.AnimaFireBlock;
import net.yezon.theabyss.block.AbyssCrystalOreBlock;
import net.yezon.theabyss.block.AboranysOreBlock;
import net.yezon.theabyss.block.AberytheOreBlock;
import net.yezon.theabyss.TheabyssMod;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.fml.event.lifecycle.FMLClientSetupEvent;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.eventbus.api.SubscribeEvent;
import net.minecraftforge.client.event.ColorHandlerEvent;
import net.minecraftforge.api.distmarker.Dist;

import net.minecraft.world.level.block.Block;

public class TheabyssModBlocks {
	public static final DeferredRegister<Block> REGISTRY = DeferredRegister.create(ForgeRegistries.BLOCKS, TheabyssMod.MODID);
	public static final RegistryObject<Block> FUSION_ORE = REGISTRY.register("fusion_ore", () -> new FusionOreBlock());
	public static final RegistryObject<Block> LORAN_ORE = REGISTRY.register("loran_ore", () -> new LoranOreBlock());
	public static final RegistryObject<Block> GARNITE_ORE = REGISTRY.register("garnite_ore", () -> new GarniteOreBlock());
	public static final RegistryObject<Block> IGNISITHE_ORE = REGISTRY.register("ignisithe_ore", () -> new IgnisitheOreBlock());
	public static final RegistryObject<Block> ABORANYS_ORE = REGISTRY.register("aboranys_ore", () -> new AboranysOreBlock());
	public static final RegistryObject<Block> GLACERYTHE_ORE = REGISTRY.register("glacerythe_ore", () -> new GlacerytheOreBlock());
	public static final RegistryObject<Block> ABERYTHE_ORE = REGISTRY.register("aberythe_ore", () -> new AberytheOreBlock());
	public static final RegistryObject<Block> INCORYTHE_ORE = REGISTRY.register("incorythe_ore", () -> new IncorytheOreBlock());
	public static final RegistryObject<Block> DIAMOND_VARIANT = REGISTRY.register("diamond_variant", () -> new DiamondVariantBlock());
	public static final RegistryObject<Block> GOLD_VARIANT = REGISTRY.register("gold_variant", () -> new GoldVariantBlock());
	public static final RegistryObject<Block> IRON_VARIANT = REGISTRY.register("iron_variant", () -> new IronVariantBlock());
	public static final RegistryObject<Block> EMERALD_VARIANT = REGISTRY.register("emerald_variant", () -> new EmeraldVariantBlock());
	public static final RegistryObject<Block> FLORITE_ORE = REGISTRY.register("florite_ore", () -> new FloriteOreBlock());
	public static final RegistryObject<Block> FROST_WORLD_PORTAL = REGISTRY.register("frost_world_portal",
			() -> new TheabyssdimiceworldPortalBlock());
	public static final RegistryObject<Block> THE_ABYSS_PORTAL = REGISTRY.register("the_abyss_portal", () -> new TheAbyssDimPortalBlock());
	public static final RegistryObject<Block> GROUND_LANDS_PORTAL = REGISTRY.register("ground_lands_portal",
			() -> new TheAbyssDimGroundlandsPortalBlock());
	public static final RegistryObject<Block> ROMA_MUD = REGISTRY.register("roma_mud", () -> new RomaMudBlock());
	public static final RegistryObject<Block> ROMA_MUD_2 = REGISTRY.register("roma_mud_2", () -> new RomaMud2Block());
	public static final RegistryObject<Block> DARK_STONE = REGISTRY.register("dark_stone", () -> new DarkStoneBlock());
	public static final RegistryObject<Block> SNOW_BLOCK = REGISTRY.register("snow_block", () -> new SnowBlockBlock());
	public static final RegistryObject<Block> BLARU_LEAVES = REGISTRY.register("blaru_leaves", () -> new BlaruLeavesBlock());
	public static final RegistryObject<Block> JUNGLE_LEAVES = REGISTRY.register("jungle_leaves", () -> new JungleLeavesBlock());
	public static final RegistryObject<Block> LORKA_LEAVES = REGISTRY.register("lorka_leaves", () -> new LorkaLeavesBlock());
	public static final RegistryObject<Block> TANTRA_LEAVES = REGISTRY.register("tantra_leaves", () -> new TantraLeavesBlock());
	public static final RegistryObject<Block> ROGGEN_LEAVE = REGISTRY.register("roggen_leave", () -> new RoggenLeaveBlock());
	public static final RegistryObject<Block> FROZEN_LEAVES = REGISTRY.register("frozen_leaves", () -> new FrozenLeavesBlock());
	public static final RegistryObject<Block> RUMA_LEAVE = REGISTRY.register("ruma_leave", () -> new RumaLeaveBlock());
	public static final RegistryObject<Block> RUMA_LEAVE_2 = REGISTRY.register("ruma_leave_2", () -> new RumaLeave2Block());
	public static final RegistryObject<Block> RUMA_LEAVE_3 = REGISTRY.register("ruma_leave_3", () -> new RumaLeave3Block());
	public static final RegistryObject<Block> RUMA_LEAVE_4 = REGISTRY.register("ruma_leave_4", () -> new RumaLeave4Block());
	public static final RegistryObject<Block> RUMA_LEAVE_5 = REGISTRY.register("ruma_leave_5", () -> new RumaLeave5Block());
	public static final RegistryObject<Block> WART = REGISTRY.register("wart", () -> new WartBlock());
	public static final RegistryObject<Block> BOG_SHROOM_LEAVE = REGISTRY.register("bog_shroom_leave", () -> new BogShroomLeaveBlock());
	public static final RegistryObject<Block> SAL_SHROOM_LEAVE = REGISTRY.register("sal_shroom_leave", () -> new SalShroomLeaveBlock());
	public static final RegistryObject<Block> SLIME_BLOCK = REGISTRY.register("slime_block", () -> new SlimeBlockBlock());
	public static final RegistryObject<Block> ROTTEN_FUNGAL_LEAVE = REGISTRY.register("rotten_fungal_leave", () -> new RottenFungalLeaveBlock());
	public static final RegistryObject<Block> JUNGLE_MELON = REGISTRY.register("jungle_melon", () -> new JungleMelonBlock());
	public static final RegistryObject<Block> ROTTEN_LOG = REGISTRY.register("rotten_log", () -> new RottenLogBlock());
	public static final RegistryObject<Block> TANTRA_GRASS = REGISTRY.register("tantra_grass", () -> new TantraGrassBlock());
	public static final RegistryObject<Block> TANTRA_DIRT = REGISTRY.register("tantra_dirt", () -> new TantraDirtBlock());
	public static final RegistryObject<Block> TANTRA_STONE = REGISTRY.register("tantra_stone", () -> new TantraStoneBlock());
	public static final RegistryObject<Block> TANTRA_COBBLESTONE = REGISTRY.register("tantra_cobblestone", () -> new TantraCobblestoneBlock());
	public static final RegistryObject<Block> UNSTABLE_OBSIDIAN = REGISTRY.register("unstable_obsidian", () -> new UnstableObsidianBlock());
	public static final RegistryObject<Block> INFUSED_MAGMA = REGISTRY.register("infused_magma", () -> new InfusedMagmaBlock());
	public static final RegistryObject<Block> BONE = REGISTRY.register("bone", () -> new BoneBlock());
	public static final RegistryObject<Block> BONE_THIN = REGISTRY.register("bone_thin", () -> new BoneThinBlock());
	public static final RegistryObject<Block> BLARU_LOG = REGISTRY.register("blaru_log", () -> new BlaruLogBlock());
	public static final RegistryObject<Block> STRIPPED_BLARU_LOG = REGISTRY.register("stripped_blaru_log", () -> new StrippedBlaruLogBlock());
	public static final RegistryObject<Block> BLARU_PLANKS = REGISTRY.register("blaru_planks", () -> new BlaruPlanksBlock());
	public static final RegistryObject<Block> BLARU_STAIRS = REGISTRY.register("blaru_stairs", () -> new BlaruStairsBlock());
	public static final RegistryObject<Block> BLARU_SLAB = REGISTRY.register("blaru_slab", () -> new BlaruSlabBlock());
	public static final RegistryObject<Block> BLARU_TRAP_DOOR = REGISTRY.register("blaru_trap_door", () -> new BlaruTrapDoorBlock());
	public static final RegistryObject<Block> BLARU_DOOR = REGISTRY.register("blaru_door", () -> new BlaruDoorBlock());
	public static final RegistryObject<Block> BLARU_FENCE = REGISTRY.register("blaru_fence", () -> new BlaruFenceBlock());
	public static final RegistryObject<Block> BLARU_FENCE_GATE = REGISTRY.register("blaru_fence_gate", () -> new BlaruFenceGateBlock());
	public static final RegistryObject<Block> BLARU_PRESSURE_PLATE = REGISTRY.register("blaru_pressure_plate", () -> new BlaruPressurePlateBlock());
	public static final RegistryObject<Block> BLARU_BUTTON = REGISTRY.register("blaru_button", () -> new BlaruButtonBlock());
	public static final RegistryObject<Block> BLARU_TABLE = REGISTRY.register("blaru_table", () -> new BlaruTableBlock());
	public static final RegistryObject<Block> BLARU_CHAIR = REGISTRY.register("blaru_chair", () -> new BlaruChairBlock());
	public static final RegistryObject<Block> BLARU_LADDER = REGISTRY.register("blaru_ladder", () -> new BlaruLadderBlock());
	public static final RegistryObject<Block> BLARU_BOOKSHELF = REGISTRY.register("blaru_bookshelf", () -> new BlaruBookshelfBlock());
	public static final RegistryObject<Block> JUNGLE_LOG = REGISTRY.register("jungle_log", () -> new JungleLogBlock());
	public static final RegistryObject<Block> STIPPED_JUNGLE_LOG = REGISTRY.register("stipped_jungle_log", () -> new StippedJungleLogBlock());
	public static final RegistryObject<Block> JUNGLE_PLANKS = REGISTRY.register("jungle_planks", () -> new JunglePlanksBlock());
	public static final RegistryObject<Block> JUNGLE_STAIRS = REGISTRY.register("jungle_stairs", () -> new JungleStairsBlock());
	public static final RegistryObject<Block> JUNGLE_SLAB = REGISTRY.register("jungle_slab", () -> new JungleSlabBlock());
	public static final RegistryObject<Block> JUNGLE_TRAP_DOOR = REGISTRY.register("jungle_trap_door", () -> new JungleTrapDoorBlock());
	public static final RegistryObject<Block> JUNGLE_DOOR = REGISTRY.register("jungle_door", () -> new JungleDoorBlock());
	public static final RegistryObject<Block> JUNGLE_FENCE = REGISTRY.register("jungle_fence", () -> new JungleFenceBlock());
	public static final RegistryObject<Block> JUNGLE_FENCE_GATE = REGISTRY.register("jungle_fence_gate", () -> new JungleFenceGateBlock());
	public static final RegistryObject<Block> JUNGLE_PRESSURE_PLATE = REGISTRY.register("jungle_pressure_plate",
			() -> new JunglePressurePlateBlock());
	public static final RegistryObject<Block> JUNGLE_BUTTON = REGISTRY.register("jungle_button", () -> new JungleButtonBlock());
	public static final RegistryObject<Block> JUNGLE_CHAIR = REGISTRY.register("jungle_chair", () -> new JungleChairBlock());
	public static final RegistryObject<Block> JUNGLE_TABLE = REGISTRY.register("jungle_table", () -> new JungleTableBlock());
	public static final RegistryObject<Block> JUNGLE_LADDER = REGISTRY.register("jungle_ladder", () -> new JungleLadderBlock());
	public static final RegistryObject<Block> JUNGLE_BOOKSHELF = REGISTRY.register("jungle_bookshelf", () -> new JungleBookshelfBlock());
	public static final RegistryObject<Block> RUMA_LOG = REGISTRY.register("ruma_log", () -> new RumaLogBlock());
	public static final RegistryObject<Block> STRIPPED_RUMA_LOG = REGISTRY.register("stripped_ruma_log", () -> new StrippedRumaLogBlock());
	public static final RegistryObject<Block> RUMA_PLANKS = REGISTRY.register("ruma_planks", () -> new RumaPlanksBlock());
	public static final RegistryObject<Block> RUMA_STAIRS = REGISTRY.register("ruma_stairs", () -> new RumaStairsBlock());
	public static final RegistryObject<Block> RUMA_SLAB = REGISTRY.register("ruma_slab", () -> new RumaSlabBlock());
	public static final RegistryObject<Block> RUMA_TRAP_DOOR = REGISTRY.register("ruma_trap_door", () -> new RumaTrapDoorBlock());
	public static final RegistryObject<Block> RUMA_DOOR = REGISTRY.register("ruma_door", () -> new RumaDoorBlock());
	public static final RegistryObject<Block> RUMA_FENCE = REGISTRY.register("ruma_fence", () -> new RumaFenceBlock());
	public static final RegistryObject<Block> RUMA_FENCE_GATE = REGISTRY.register("ruma_fence_gate", () -> new RumaFenceGateBlock());
	public static final RegistryObject<Block> RUMA_PRESSURE_PLATE = REGISTRY.register("ruma_pressure_plate", () -> new RumaPressurePlateBlock());
	public static final RegistryObject<Block> RUMA_BUTTON = REGISTRY.register("ruma_button", () -> new RumaButtonBlock());
	public static final RegistryObject<Block> RUMA_CHAIR = REGISTRY.register("ruma_chair", () -> new RumaChairBlock());
	public static final RegistryObject<Block> RUMA_TABLE = REGISTRY.register("ruma_table", () -> new RumaTableBlock());
	public static final RegistryObject<Block> RUMA_LADDER = REGISTRY.register("ruma_ladder", () -> new RumaLadderBlock());
	public static final RegistryObject<Block> RUMA_BOOKSHELF = REGISTRY.register("ruma_bookshelf", () -> new RumaBookshelfBlock());
	public static final RegistryObject<Block> ROGGEN_LOG = REGISTRY.register("roggen_log", () -> new RoggenLogBlock());
	public static final RegistryObject<Block> STRIPPED_ROGGEN_LOG = REGISTRY.register("stripped_roggen_log", () -> new StrippedRoggenLogBlock());
	public static final RegistryObject<Block> ROGGEN_PLANKS = REGISTRY.register("roggen_planks", () -> new RoggenPlanksBlock());
	public static final RegistryObject<Block> ROGGEN_STAIRS = REGISTRY.register("roggen_stairs", () -> new RoggenStairsBlock());
	public static final RegistryObject<Block> ROGGEN_SLAB = REGISTRY.register("roggen_slab", () -> new RoggenSlabBlock());
	public static final RegistryObject<Block> ROGGEN_TRAP_DOOR = REGISTRY.register("roggen_trap_door", () -> new RoggenTrapDoorBlock());
	public static final RegistryObject<Block> ROGGEN_DOOR = REGISTRY.register("roggen_door", () -> new RoggenDoorBlock());
	public static final RegistryObject<Block> ROGGEN_FENCE = REGISTRY.register("roggen_fence", () -> new RoggenFenceBlock());
	public static final RegistryObject<Block> ROGGEN_FENCE_GATE = REGISTRY.register("roggen_fence_gate", () -> new RoggenFenceGateBlock());
	public static final RegistryObject<Block> ROGGEN_PRESSURE_PLATE = REGISTRY.register("roggen_pressure_plate",
			() -> new RoggenPressurePlateBlock());
	public static final RegistryObject<Block> ROGGEN_BUTTON = REGISTRY.register("roggen_button", () -> new RoggenButtonBlock());
	public static final RegistryObject<Block> ROGGEN_CHAIR = REGISTRY.register("roggen_chair", () -> new RoggenChairBlock());
	public static final RegistryObject<Block> ROGGEN_TABLE = REGISTRY.register("roggen_table", () -> new RoggenTableBlock());
	public static final RegistryObject<Block> ROGGEN_LADDER = REGISTRY.register("roggen_ladder", () -> new RoggenLadderBlock());
	public static final RegistryObject<Block> TANTRA_LOG = REGISTRY.register("tantra_log", () -> new TantraLogBlock());
	public static final RegistryObject<Block> STRIPPED_TANTRA_LOG = REGISTRY.register("stripped_tantra_log", () -> new StrippedTantraLogBlock());
	public static final RegistryObject<Block> TANTRA_PLANKS = REGISTRY.register("tantra_planks", () -> new TantraPlanksBlock());
	public static final RegistryObject<Block> TANTRA_STAIRS = REGISTRY.register("tantra_stairs", () -> new TantraStairsBlock());
	public static final RegistryObject<Block> TANTRA_SLAB = REGISTRY.register("tantra_slab", () -> new TantraSlabBlock());
	public static final RegistryObject<Block> TANTRA_TRAP_DOOR = REGISTRY.register("tantra_trap_door", () -> new TantraTrapDoorBlock());
	public static final RegistryObject<Block> TANTRA_DOOR = REGISTRY.register("tantra_door", () -> new TantraDoorBlock());
	public static final RegistryObject<Block> TANTRA_FENCE = REGISTRY.register("tantra_fence", () -> new TantraFenceBlock());
	public static final RegistryObject<Block> TANTRA_FENCE_GATE = REGISTRY.register("tantra_fence_gate", () -> new TantraFenceGateBlock());
	public static final RegistryObject<Block> TANTRA_PRESSURE_PLATE = REGISTRY.register("tantra_pressure_plate",
			() -> new TantraPressurePlateBlock());
	public static final RegistryObject<Block> TANTRA_BUTTON = REGISTRY.register("tantra_button", () -> new TantraButtonBlock());
	public static final RegistryObject<Block> TANTRA_CHAIR = REGISTRY.register("tantra_chair", () -> new TantraChairBlock());
	public static final RegistryObject<Block> TANTRA_TABLE = REGISTRY.register("tantra_table", () -> new TantraTableBlock());
	public static final RegistryObject<Block> TANTRA_LADDER = REGISTRY.register("tantra_ladder", () -> new TantraLadderBlock());
	public static final RegistryObject<Block> BOG_SHROOM_LOG = REGISTRY.register("bog_shroom_log", () -> new BogShroomLogBlock());
	public static final RegistryObject<Block> BOG_PLANKS = REGISTRY.register("bog_planks", () -> new BogPlanksBlock());
	public static final RegistryObject<Block> BOG_STAIRS = REGISTRY.register("bog_stairs", () -> new BogStairsBlock());
	public static final RegistryObject<Block> BOG_SLAB = REGISTRY.register("bog_slab", () -> new BogSlabBlock());
	public static final RegistryObject<Block> BOG_TRAP_DOOR = REGISTRY.register("bog_trap_door", () -> new BogTrapDoorBlock());
	public static final RegistryObject<Block> BOG_DOOR = REGISTRY.register("bog_door", () -> new BogDoorBlock());
	public static final RegistryObject<Block> BOG_FENCE = REGISTRY.register("bog_fence", () -> new BogFenceBlock());
	public static final RegistryObject<Block> BOG_FENCE_GATE = REGISTRY.register("bog_fence_gate", () -> new BogFenceGateBlock());
	public static final RegistryObject<Block> BOG_PRESSURE_PLATE = REGISTRY.register("bog_pressure_plate", () -> new BogPressurePlateBlock());
	public static final RegistryObject<Block> BOG_BUTTON = REGISTRY.register("bog_button", () -> new BogButtonBlock());
	public static final RegistryObject<Block> BOG_CHAIR = REGISTRY.register("bog_chair", () -> new BogChairBlock());
	public static final RegistryObject<Block> BOG_TABLE = REGISTRY.register("bog_table", () -> new BogTableBlock());
	public static final RegistryObject<Block> BOG_LADDER = REGISTRY.register("bog_ladder", () -> new BogLadderBlock());
	public static final RegistryObject<Block> SAL_SHROOM_LOG = REGISTRY.register("sal_shroom_log", () -> new SalShroomLogBlock());
	public static final RegistryObject<Block> SAL_PLANKS = REGISTRY.register("sal_planks", () -> new SalPlanksBlock());
	public static final RegistryObject<Block> SAL_STAIRS = REGISTRY.register("sal_stairs", () -> new SalStairsBlock());
	public static final RegistryObject<Block> SAL_SLAB = REGISTRY.register("sal_slab", () -> new SalSlabBlock());
	public static final RegistryObject<Block> SAL_TRAP_DOOR = REGISTRY.register("sal_trap_door", () -> new SalTrapDoorBlock());
	public static final RegistryObject<Block> SAL_DOOR = REGISTRY.register("sal_door", () -> new SalDoorBlock());
	public static final RegistryObject<Block> SAL_FENCE = REGISTRY.register("sal_fence", () -> new SalFenceBlock());
	public static final RegistryObject<Block> SAL_FENCE_GATE = REGISTRY.register("sal_fence_gate", () -> new SalFenceGateBlock());
	public static final RegistryObject<Block> SAL_PRESSURE_PLATE = REGISTRY.register("sal_pressure_plate", () -> new SalPressurePlateBlock());
	public static final RegistryObject<Block> SAL_BUTTON = REGISTRY.register("sal_button", () -> new SalButtonBlock());
	public static final RegistryObject<Block> SAL_CHAIR = REGISTRY.register("sal_chair", () -> new SalChairBlock());
	public static final RegistryObject<Block> SAL_TABLE = REGISTRY.register("sal_table", () -> new SalTableBlock());
	public static final RegistryObject<Block> SAL_LADDER = REGISTRY.register("sal_ladder", () -> new SalLadderBlock());
	public static final RegistryObject<Block> SLIMED_LOG = REGISTRY.register("slimed_log", () -> new SlimedLogBlock());
	public static final RegistryObject<Block> SLIMED_PLANKS = REGISTRY.register("slimed_planks", () -> new SlimedPlanksBlock());
	public static final RegistryObject<Block> SLIMED_STAIRS = REGISTRY.register("slimed_stairs", () -> new SlimedStairsBlock());
	public static final RegistryObject<Block> SLIMED_SLAB = REGISTRY.register("slimed_slab", () -> new SlimedSlabBlock());
	public static final RegistryObject<Block> SLIMED_TRAP_DOOR = REGISTRY.register("slimed_trap_door", () -> new SlimedTrapDoorBlock());
	public static final RegistryObject<Block> SLIMED_DOOR = REGISTRY.register("slimed_door", () -> new SlimedDoorBlock());
	public static final RegistryObject<Block> SLIMED_FENCE = REGISTRY.register("slimed_fence", () -> new SlimedFenceBlock());
	public static final RegistryObject<Block> SLIMED_FENCE_GATE = REGISTRY.register("slimed_fence_gate", () -> new SlimedFenceGateBlock());
	public static final RegistryObject<Block> SLIMED_PRESSURE_PLATE = REGISTRY.register("slimed_pressure_plate",
			() -> new SlimedPressurePlateBlock());
	public static final RegistryObject<Block> SLIMED_BUTTON = REGISTRY.register("slimed_button", () -> new SlimedButtonBlock());
	public static final RegistryObject<Block> SLIMED_CHAIR = REGISTRY.register("slimed_chair", () -> new SlimedChairBlock());
	public static final RegistryObject<Block> SLIMED_TABLE = REGISTRY.register("slimed_table", () -> new SlimedTableBlock());
	public static final RegistryObject<Block> SLIMED_LADDER = REGISTRY.register("slimed_ladder", () -> new SlimedLadderBlock());
	public static final RegistryObject<Block> FROZEN_LOG = REGISTRY.register("frozen_log", () -> new FrozenLogBlock());
	public static final RegistryObject<Block> FROZEN_PLANKS = REGISTRY.register("frozen_planks", () -> new FrozenPlanksBlock());
	public static final RegistryObject<Block> FROZEN_STAIRS = REGISTRY.register("frozen_stairs", () -> new FrozenStairsBlock());
	public static final RegistryObject<Block> FROZEN_SLAB = REGISTRY.register("frozen_slab", () -> new FrozenSlabBlock());
	public static final RegistryObject<Block> FROZEN_TRAP_DOOR = REGISTRY.register("frozen_trap_door", () -> new FrozenTrapDoorBlock());
	public static final RegistryObject<Block> FROZEN_DOOR = REGISTRY.register("frozen_door", () -> new FrozenDoorBlock());
	public static final RegistryObject<Block> FROZEN_FENCE = REGISTRY.register("frozen_fence", () -> new FrozenFenceBlock());
	public static final RegistryObject<Block> FROZEN_FENCE_GATE = REGISTRY.register("frozen_fence_gate", () -> new FrozenFenceGateBlock());
	public static final RegistryObject<Block> FROZEN_PRESSURE_PLATE = REGISTRY.register("frozen_pressure_plate",
			() -> new FrozenPressurePlateBlock());
	public static final RegistryObject<Block> FROZEN_BUTTON = REGISTRY.register("frozen_button", () -> new FrozenButtonBlock());
	public static final RegistryObject<Block> FROZEN_CHAIR = REGISTRY.register("frozen_chair", () -> new FrozenChairBlock());
	public static final RegistryObject<Block> FROZEN_TABLE = REGISTRY.register("frozen_table", () -> new FrozenTableBlock());
	public static final RegistryObject<Block> FROZEN_LADDER = REGISTRY.register("frozen_ladder", () -> new FrozenLadderBlock());
	public static final RegistryObject<Block> FROST_BRICK = REGISTRY.register("frost_brick", () -> new FrostBrickBlock());
	public static final RegistryObject<Block> FROST_BRICK_CRACKED = REGISTRY.register("frost_brick_cracked", () -> new FrostBrickCrackedBlock());
	public static final RegistryObject<Block> FROST_BRICK_STAIRS = REGISTRY.register("frost_brick_stairs", () -> new FrostBrickStairsBlock());
	public static final RegistryObject<Block> FROST_BRICKS_SLAB = REGISTRY.register("frost_bricks_slab", () -> new FrostBricksSlabBlock());
	public static final RegistryObject<Block> FROST_BRICK_WALL = REGISTRY.register("frost_brick_wall", () -> new FrostBrickWallBlock());
	public static final RegistryObject<Block> STONE = REGISTRY.register("stone", () -> new StoneBlock());
	public static final RegistryObject<Block> STONE_STAIRS = REGISTRY.register("stone_stairs", () -> new StoneStairsBlock());
	public static final RegistryObject<Block> STONE_SLAB = REGISTRY.register("stone_slab", () -> new StoneSlabsBlock());
	public static final RegistryObject<Block> COBBLE_STONE_STAIRS = REGISTRY.register("cobble_stone_stairs", () -> new CobbleStoneStairsBlock());
	public static final RegistryObject<Block> COBBLE_STONE_SLAB = REGISTRY.register("cobble_stone_slab", () -> new CobbleStoneSlabBlock());
	public static final RegistryObject<Block> COBBLE_STONE_WALL = REGISTRY.register("cobble_stone_wall", () -> new CobbleStoneWallBlock());
	public static final RegistryObject<Block> COBBLE_STONE = REGISTRY.register("cobble_stone", () -> new CobbleStoneBlock());
	public static final RegistryObject<Block> STONE_BRICK_STAIRS = REGISTRY.register("stone_brick_stairs", () -> new StoneBrickStairsBlock());
	public static final RegistryObject<Block> STONE_BRICK = REGISTRY.register("stone_brick", () -> new StoneBrickBlock());
	public static final RegistryObject<Block> STONE_BRICK_BROKEN = REGISTRY.register("stone_brick_broken", () -> new StoneBrickBrokenBlock());
	public static final RegistryObject<Block> STONE_BRICK_CHISELED = REGISTRY.register("stone_brick_chiseled", () -> new StoneBrickChiseledBlock());
	public static final RegistryObject<Block> STONE_BRICK_SLAB = REGISTRY.register("stone_brick_slab", () -> new StoneBrickSlabBlock());
	public static final RegistryObject<Block> NIGHT_ALTAR = REGISTRY.register("night_altar", () -> new NightAltarBlock());
	public static final RegistryObject<Block> NIGHT_ALTAR_ACTIVATED = REGISTRY.register("night_altar_activated",
			() -> new NightAltarActivatedBlock());
	public static final RegistryObject<Block> STONE_BRICK_WALL = REGISTRY.register("stone_brick_wall", () -> new StoneBrickWallBlock());
	public static final RegistryObject<Block> STONE_BRICK_PILLAR_IGNITED = REGISTRY.register("stone_brick_pillar_ignited",
			() -> new StoneBrickPillarIgnitedBlock());
	public static final RegistryObject<Block> STONE_BRICK_PILLAR = REGISTRY.register("stone_brick_pillar", () -> new StoneBrickPillarBlock());
	public static final RegistryObject<Block> PHANTOM_LANTERN = REGISTRY.register("phantom_lantern", () -> new PhantomLanternBlock());
	public static final RegistryObject<Block> ENDER_LANTERN = REGISTRY.register("ender_lantern", () -> new EnderLanternBlock());
	public static final RegistryObject<Block> HOGLIN_LANTERN = REGISTRY.register("hoglin_lantern", () -> new HoglinLanternBlock());
	public static final RegistryObject<Block> BLUE_SHROOMLIGHT = REGISTRY.register("blue_shroomlight", () -> new BlueShroomlightBlock());
	public static final RegistryObject<Block> DARK_BLUE_SHROOMLIGHT = REGISTRY.register("dark_blue_shroomlight",
			() -> new DarkBlueShroomlightBlock());
	public static final RegistryObject<Block> PURPLE_SHROOMLIGHT = REGISTRY.register("purple_shroomlight", () -> new PurpleShroomlightBlock());
	public static final RegistryObject<Block> SLIME_ROOT_BLOCK = REGISTRY.register("slime_root_block", () -> new SlimeRootBlockBlock());
	public static final RegistryObject<Block> HEAL_CAMP_FIRE = REGISTRY.register("heal_camp_fire", () -> new HealCampFireBlock());
	public static final RegistryObject<Block> SHIELD_CAMP_FIRE = REGISTRY.register("shield_camp_fire", () -> new ShieldCampFireBlock());
	public static final RegistryObject<Block> DIRT = REGISTRY.register("dirt", () -> new DirtBlock());
	public static final RegistryObject<Block> BROKEN_RADIO = REGISTRY.register("broken_radio", () -> new BrokenRadioBlock());
	public static final RegistryObject<Block> SOMNIUM_EXTRACTOR = REGISTRY.register("somnium_extractor", () -> new SomniumExtractorBlock());
	public static final RegistryObject<Block> ARCANE_WORKBENCH = REGISTRY.register("arcane_workbench", () -> new ArcaneWorkbenchBlock());
	public static final RegistryObject<Block> RESEARCH_TABLE = REGISTRY.register("research_table", () -> new ResearchTableBlock());
	public static final RegistryObject<Block> CRYSTAL_CUTTER = REGISTRY.register("crystal_cutter", () -> new CrystalCutterBlock());
	public static final RegistryObject<Block> SOMNIUM_INFUSER = REGISTRY.register("somnium_infuser", () -> new SomniumInfuserBlock());
	public static final RegistryObject<Block> MORTAR_AND_PESTLE = REGISTRY.register("mortar_and_pestle", () -> new MortarAndPestleBlock());
	public static final RegistryObject<Block> BLACK_VOID = REGISTRY.register("black_void", () -> new BlackVoidBlock());
	public static final RegistryObject<Block> ARENO = REGISTRY.register("areno", () -> new ArenoBlock());
	public static final RegistryObject<Block> INFECTED_PEAT = REGISTRY.register("infected_peat", () -> new InfectedPeatBlock());
	public static final RegistryObject<Block> ROTTEN_LEAVE = REGISTRY.register("rotten_leave", () -> new RottenLeaveBlock());
	public static final RegistryObject<Block> GRAVEL = REGISTRY.register("gravel", () -> new InfectedGravelBlock());
	public static final RegistryObject<Block> INFECTED_GRASS = REGISTRY.register("infected_grass", () -> new InfectedGrassBlock());
	public static final RegistryObject<Block> BLARU_MOSS = REGISTRY.register("blaru_moss", () -> new BlaruMossBlock());
	public static final RegistryObject<Block> LORAN_FLOWER = REGISTRY.register("loran_flower", () -> new LoranFlowerBlock());
	public static final RegistryObject<Block> GULOM_PLANT = REGISTRY.register("gulom_plant", () -> new GulomPlantBlock());
	public static final RegistryObject<Block> RALOM_PLANT = REGISTRY.register("ralom_plant", () -> new RalomPlantBlock());
	public static final RegistryObject<Block> FORTIS_ULTIMA = REGISTRY.register("fortis_ultima", () -> new FortisUltimaBlock());
	public static final RegistryObject<Block> OPIA_SHROOM = REGISTRY.register("opia_shroom", () -> new OpiaShroomBlock());
	public static final RegistryObject<Block> THUNDER_FLOWER = REGISTRY.register("thunder_flower", () -> new ThunderFlowerBlock());
	public static final RegistryObject<Block> LERCAS_UMBRELLA = REGISTRY.register("lercas_umbrella", () -> new LercasUmbrellaBlock());
	public static final RegistryObject<Block> SRALA_SHROOM = REGISTRY.register("srala_shroom", () -> new SralaShroomBlock());
	public static final RegistryObject<Block> SATURNIA_VERSA = REGISTRY.register("saturnia_versa", () -> new SaturniaVersaBlock());
	public static final RegistryObject<Block> LUMUS_MAXIMUS = REGISTRY.register("lumus_maximus", () -> new LumusMaximusBlock());
	public static final RegistryObject<Block> VERA_LESUS = REGISTRY.register("vera_lesus", () -> new VeraLesusBlock());
	public static final RegistryObject<Block> OCTAVYS_MAGYNISIUS = REGISTRY.register("octavys_magynisius", () -> new OctavysMagynisiusBlock());
	public static final RegistryObject<Block> CAECUS_VERSA = REGISTRY.register("caecus_versa", () -> new CaecusVersaBlock());
	public static final RegistryObject<Block> FLOS_VITAE = REGISTRY.register("flos_vitae", () -> new FlosVitaeBlock());
	public static final RegistryObject<Block> LERA_EXILIARIS = REGISTRY.register("lera_exiliaris", () -> new LeraExiliarisBlock());
	public static final RegistryObject<Block> IGNETARIS_VERSA = REGISTRY.register("ignetaris_versa", () -> new IgnetarisVersaBlock());
	public static final RegistryObject<Block> GORALYS_LASUS = REGISTRY.register("goralys_lasus", () -> new GoralysLasusBlock());
	public static final RegistryObject<Block> WART_ROOT = REGISTRY.register("wart_root", () -> new WartRootBlock());
	public static final RegistryObject<Block> LORAN_BUSH_2 = REGISTRY.register("loran_bush_2", () -> new LoranBush2Block());
	public static final RegistryObject<Block> LORAN_BUSH = REGISTRY.register("loran_bush", () -> new LoranBushBlock());
	public static final RegistryObject<Block> TENUEM_FIRE = REGISTRY.register("tenuem_fire", () -> new TenuemFireBlock());
	public static final RegistryObject<Block> ANIMA_FIRE = REGISTRY.register("anima_fire", () -> new AnimaFireBlock());
	public static final RegistryObject<Block> SLIMED_VITAE = REGISTRY.register("slimed_vitae", () -> new SlimedVitaeBlock());
	public static final RegistryObject<Block> ICE_RANK = REGISTRY.register("ice_rank", () -> new IceRankBlock());
	public static final RegistryObject<Block> ICORA_FLOWER = REGISTRY.register("icora_flower", () -> new IcoraFlowerBlock());
	public static final RegistryObject<Block> TESLA_RANK = REGISTRY.register("tesla_rank", () -> new TeslaRankBlock());
	public static final RegistryObject<Block> ICELA_RANK = REGISTRY.register("icela_rank", () -> new IcelaRankBlock());
	public static final RegistryObject<Block> ROTTEN_RANK = REGISTRY.register("rotten_rank", () -> new RottenRankBlock());
	public static final RegistryObject<Block> WART_RANK = REGISTRY.register("wart_rank", () -> new WartRankBlock());
	public static final RegistryObject<Block> WART_RANK_END = REGISTRY.register("wart_rank_end", () -> new WartRankEndBlock());
	public static final RegistryObject<Block> GRASS_SMALL = REGISTRY.register("grass_small", () -> new GrassSmallBlock());
	public static final RegistryObject<Block> GRASS_MIDDLE = REGISTRY.register("grass_middle", () -> new GrassMiddleBlock());
	public static final RegistryObject<Block> GRASS_BIG = REGISTRY.register("grass_big", () -> new GrassBigBlock());
	public static final RegistryObject<Block> TALL_GLOW_SHROOM = REGISTRY.register("tall_glow_shroom", () -> new TallGlowShroomBlock());
	public static final RegistryObject<Block> GLOW_SHROOM = REGISTRY.register("glow_shroom", () -> new GlowShroomBlock());
	public static final RegistryObject<Block> TALL_RUB_SHROOM = REGISTRY.register("tall_rub_shroom", () -> new TallRubShroomBlock());
	public static final RegistryObject<Block> RUB_SHROOM = REGISTRY.register("rub_shroom", () -> new RubShroomBlock());
	public static final RegistryObject<Block> VERTA_CELSIUS = REGISTRY.register("verta_celsius", () -> new VertaCelsiusBlock());
	public static final RegistryObject<Block> SLIMED_LOG_FUNGI = REGISTRY.register("slimed_log_fungi", () -> new SlimedLogFungiBlock());
	public static final RegistryObject<Block> BLARU_LOG_FUNGI = REGISTRY.register("blaru_log_fungi", () -> new BlaruLogFungiBlock());
	public static final RegistryObject<Block> JUNGLE_LOG_FUNGI = REGISTRY.register("jungle_log_fungi", () -> new JungleLogFungiBlock());
	public static final RegistryObject<Block> BOG_LOG_FUNGI = REGISTRY.register("bog_log_fungi", () -> new BogLogFungiBlock());
	public static final RegistryObject<Block> RUMA_LOG_FUNGI = REGISTRY.register("ruma_log_fungi", () -> new RumaLogFungiBlock());
	public static final RegistryObject<Block> RUMA_LOG_FUNGI_2 = REGISTRY.register("ruma_log_fungi_2", () -> new RumaLogFungi2Block());
	public static final RegistryObject<Block> SAL_LOG_FUNGI = REGISTRY.register("sal_log_fungi", () -> new SalLogFungiBlock());
	public static final RegistryObject<Block> MINI_STONE_1 = REGISTRY.register("mini_stone_1", () -> new MiniStone1Block());
	public static final RegistryObject<Block> BOG_VINE = REGISTRY.register("bog_vine", () -> new BogVineBlock());
	public static final RegistryObject<Block> TANTRA_VINE = REGISTRY.register("tantra_vine", () -> new TantraVineBlock());
	public static final RegistryObject<Block> SAL_VINE = REGISTRY.register("sal_vine", () -> new SalVineBlock());
	public static final RegistryObject<Block> ROGGEN_VINE = REGISTRY.register("roggen_vine", () -> new RoggenVineBlock());
	public static final RegistryObject<Block> ROTTEN_LOG_VINE = REGISTRY.register("rotten_log_vine", () -> new RottenLogVineBlock());
	public static final RegistryObject<Block> SLIMED_LOG_VINE = REGISTRY.register("slimed_log_vine", () -> new SlimedLogVineBlock());
	public static final RegistryObject<Block> JUNGLE_LOG_VINE = REGISTRY.register("jungle_log_vine", () -> new JungleLogVineBlock());
	public static final RegistryObject<Block> FROZEN_LOG_VINE = REGISTRY.register("frozen_log_vine", () -> new FrozenLogVineBlock());
	public static final RegistryObject<Block> RUMA_LOG_VINE = REGISTRY.register("ruma_log_vine", () -> new RumaLogVineBlock());
	public static final RegistryObject<Block> BLARU_LOG_VINE = REGISTRY.register("blaru_log_vine", () -> new BlaruLogVineBlock());
	public static final RegistryObject<Block> JUNGLE_VINE = REGISTRY.register("jungle_vine", () -> new JungleVineBlock());
	public static final RegistryObject<Block> BLARU_VINE = REGISTRY.register("blaru_vine", () -> new BlaruVineBlock());
	public static final RegistryObject<Block> LORKA_VINE = REGISTRY.register("lorka_vine", () -> new LorkaVineBlock());
	public static final RegistryObject<Block> SLIMED_LOG_CRYSTAL = REGISTRY.register("slimed_log_crystal", () -> new SlimedLogCrystalBlock());
	public static final RegistryObject<Block> TANTRA_GRASS_SMALL = REGISTRY.register("tantra_grass_small", () -> new TantraGrassSmallBlock());
	public static final RegistryObject<Block> TANTRA_GRASS_MIDDLE = REGISTRY.register("tantra_grass_middle", () -> new TantraGrassMiddleBlock());
	public static final RegistryObject<Block> TANTRA_GRASS_BIG = REGISTRY.register("tantra_grass_big", () -> new TantraGrassBigBlock());
	public static final RegistryObject<Block> LAZARUS_GRASS = REGISTRY.register("lazarus_grass", () -> new LazarusGrassBlock());
	public static final RegistryObject<Block> LUMUS_GRASS = REGISTRY.register("lumus_grass", () -> new LumusGrassBlock());
	public static final RegistryObject<Block> LUMUS_FLOWER = REGISTRY.register("lumus_flower", () -> new LumusFlowerBlock());
	public static final RegistryObject<Block> LUMUS_RANK = REGISTRY.register("lumus_rank", () -> new LumusRankBlock());
	public static final RegistryObject<Block> LUMUS_FRUIT = REGISTRY.register("lumus_fruit", () -> new LumusFruitBlock());
	public static final RegistryObject<Block> VEALUS_MERAMUS = REGISTRY.register("vealus_meramus", () -> new VealusMeramusBlock());
	public static final RegistryObject<Block> CRIMSON_CRYSTAL_ORE = REGISTRY.register("crimson_crystal_ore", () -> new CrimsonCrystalOreBlock());
	public static final RegistryObject<Block> WARPED_CRYSTAL_ORE = REGISTRY.register("warped_crystal_ore", () -> new WarpedCrystalOreBlock());
	public static final RegistryObject<Block> AUREL_CRYSTAL_ORE = REGISTRY.register("aurel_crystal_ore", () -> new AurelCrystalOreBlock());
	public static final RegistryObject<Block> CAVERNA_CRYSTAL_ORE = REGISTRY.register("caverna_crystal_ore", () -> new CavernaCrystalOreBlock());
	public static final RegistryObject<Block> ENDER_CRYSTAL_ORE = REGISTRY.register("ender_crystal_ore", () -> new EnderCrystalOreBlock());
	public static final RegistryObject<Block> FROST_CRYSTAL_ORE = REGISTRY.register("frost_crystal_ore", () -> new FrostCrystalOreBlock());
	public static final RegistryObject<Block> ABYSS_CRYSTAL_ORE = REGISTRY.register("abyss_crystal_ore", () -> new AbyssCrystalOreBlock());
	public static final RegistryObject<Block> HOLLOW_CRYSTAL_ORE = REGISTRY.register("hollow_crystal_ore", () -> new HollowCrystalOreBlock());
	public static final RegistryObject<Block> EXOLIUS_PLANT = REGISTRY.register("exolius_plant", () -> new ExoliusPlantBlock());
	public static final RegistryObject<Block> YOUNG_EXOLIUS_PLANT = REGISTRY.register("young_exolius_plant", () -> new YoungExoliusPlantBlock());
	public static final RegistryObject<Block> BLARU_LEAVE_CARPET = REGISTRY.register("blaru_leave_carpet", () -> new BlaruLeaveCarpetBlock());
	public static final RegistryObject<Block> JUNGLE_LEAVE_CARPET = REGISTRY.register("jungle_leave_carpet", () -> new JungleLeaveCarpetBlock());
	public static final RegistryObject<Block> SLIMED_CARPET = REGISTRY.register("slimed_carpet", () -> new SlimedCarpetBlock());
	public static final RegistryObject<Block> LUNGO_RANK = REGISTRY.register("lungo_rank", () -> new LungoRankBlock());
	public static final RegistryObject<Block> GLOWING_BLARU_MOSS = REGISTRY.register("glowing_blaru_moss", () -> new GlowingBlaruMossBlock());
	public static final RegistryObject<Block> AUREL_CAVE_MOSS = REGISTRY.register("aurel_cave_moss", () -> new AurelCaveMossBlock());
	public static final RegistryObject<Block> AUREL_SHROOM = REGISTRY.register("aurel_shroom", () -> new AurelShroomBlock());
	public static final RegistryObject<Block> AUREL_LEAVE_CARPET = REGISTRY.register("aurel_leave_carpet", () -> new AurelLeaveCarpetBlock());
	public static final RegistryObject<Block> AUREL_RANK = REGISTRY.register("aurel_rank", () -> new AurelRankBlock());
	public static final RegistryObject<Block> BLARU_CAVE_MOSS = REGISTRY.register("blaru_cave_moss", () -> new BlaruCaveMossBlock());
	public static final RegistryObject<Block> ECHOLOT_TOP = REGISTRY.register("echolot_top", () -> new EcholotTopBlock());
	public static final RegistryObject<Block> ECHOLOT_MIDDLE = REGISTRY.register("echolot_middle", () -> new EcholotMiddleBlock());
	public static final RegistryObject<Block> ECHOLOT_BOTTOM = REGISTRY.register("echolot_bottom", () -> new EcholotBottomBlock());
	public static final RegistryObject<Block> LUMA_GRASS = REGISTRY.register("luma_grass", () -> new LumaGrassBlock());
	public static final RegistryObject<Block> PHANTOM_HANGING_LANTERN = REGISTRY.register("phantom_hanging_lantern",
			() -> new PhantomHangingLanternBlock());
	public static final RegistryObject<Block> ENDER_HANGING_LANTERN = REGISTRY.register("ender_hanging_lantern",
			() -> new EnderHangingLanternBlock());
	public static final RegistryObject<Block> HOGLIN_HANGING_LANTERN = REGISTRY.register("hoglin_hanging_lantern",
			() -> new HoglinHangingLanternBlock());
	public static final RegistryObject<Block> RAPTOR_EGG = REGISTRY.register("raptor_egg", () -> new RaptorEggBlock());
	public static final RegistryObject<Block> WATER_ECHOLOT_TOP = REGISTRY.register("water_echolot_top", () -> new WaterEcholotTopBlock());
	public static final RegistryObject<Block> WATER_ECHOLOT_MIDDLE = REGISTRY.register("water_echolot_middle", () -> new WaterEcholotMiddleBlock());
	public static final RegistryObject<Block> WATER_ECHOLOT_BOTTOM = REGISTRY.register("water_echolot_bottom", () -> new WaterEcholotBottomBlock());
	public static final RegistryObject<Block> SLIMED_RANK = REGISTRY.register("slimed_rank", () -> new SlimedRankBlock());

	@Mod.EventBusSubscriber(bus = Mod.EventBusSubscriber.Bus.MOD, value = Dist.CLIENT)
	public static class ClientSideHandler {
		@SubscribeEvent
		public static void clientSetup(FMLClientSetupEvent event) {
			BlaruLeavesBlock.registerRenderLayer();
			JungleLeavesBlock.registerRenderLayer();
			LorkaLeavesBlock.registerRenderLayer();
			TantraLeavesBlock.registerRenderLayer();
			RoggenLeaveBlock.registerRenderLayer();
			FrozenLeavesBlock.registerRenderLayer();
			RumaLeaveBlock.registerRenderLayer();
			RumaLeave2Block.registerRenderLayer();
			RumaLeave3Block.registerRenderLayer();
			RumaLeave4Block.registerRenderLayer();
			RumaLeave5Block.registerRenderLayer();
			BogShroomLeaveBlock.registerRenderLayer();
			SalShroomLeaveBlock.registerRenderLayer();
			SlimeBlockBlock.registerRenderLayer();
			RottenFungalLeaveBlock.registerRenderLayer();
			TantraGrassBlock.registerRenderLayer();
			TantraDirtBlock.registerRenderLayer();
			BlaruStairsBlock.registerRenderLayer();
			BlaruSlabBlock.registerRenderLayer();
			BlaruTrapDoorBlock.registerRenderLayer();
			BlaruDoorBlock.registerRenderLayer();
			BlaruFenceBlock.registerRenderLayer();
			BlaruFenceGateBlock.registerRenderLayer();
			BlaruPressurePlateBlock.registerRenderLayer();
			BlaruTableBlock.registerRenderLayer();
			BlaruChairBlock.registerRenderLayer();
			BlaruLadderBlock.registerRenderLayer();
			JungleStairsBlock.registerRenderLayer();
			JungleSlabBlock.registerRenderLayer();
			JungleTrapDoorBlock.registerRenderLayer();
			JungleDoorBlock.registerRenderLayer();
			JungleFenceBlock.registerRenderLayer();
			JungleFenceGateBlock.registerRenderLayer();
			JunglePressurePlateBlock.registerRenderLayer();
			JungleChairBlock.registerRenderLayer();
			JungleTableBlock.registerRenderLayer();
			JungleLadderBlock.registerRenderLayer();
			RumaStairsBlock.registerRenderLayer();
			RumaSlabBlock.registerRenderLayer();
			RumaTrapDoorBlock.registerRenderLayer();
			RumaDoorBlock.registerRenderLayer();
			RumaFenceBlock.registerRenderLayer();
			RumaFenceGateBlock.registerRenderLayer();
			RumaPressurePlateBlock.registerRenderLayer();
			RumaChairBlock.registerRenderLayer();
			RumaTableBlock.registerRenderLayer();
			RumaLadderBlock.registerRenderLayer();
			RoggenStairsBlock.registerRenderLayer();
			RoggenSlabBlock.registerRenderLayer();
			RoggenTrapDoorBlock.registerRenderLayer();
			RoggenDoorBlock.registerRenderLayer();
			RoggenFenceBlock.registerRenderLayer();
			RoggenFenceGateBlock.registerRenderLayer();
			RoggenPressurePlateBlock.registerRenderLayer();
			RoggenChairBlock.registerRenderLayer();
			RoggenTableBlock.registerRenderLayer();
			RoggenLadderBlock.registerRenderLayer();
			TantraStairsBlock.registerRenderLayer();
			TantraSlabBlock.registerRenderLayer();
			TantraTrapDoorBlock.registerRenderLayer();
			TantraDoorBlock.registerRenderLayer();
			TantraFenceBlock.registerRenderLayer();
			TantraFenceGateBlock.registerRenderLayer();
			TantraPressurePlateBlock.registerRenderLayer();
			TantraChairBlock.registerRenderLayer();
			TantraTableBlock.registerRenderLayer();
			TantraLadderBlock.registerRenderLayer();
			BogDoorBlock.registerRenderLayer();
			BogChairBlock.registerRenderLayer();
			BogTableBlock.registerRenderLayer();
			BogLadderBlock.registerRenderLayer();
			SalDoorBlock.registerRenderLayer();
			SalChairBlock.registerRenderLayer();
			SalTableBlock.registerRenderLayer();
			SalLadderBlock.registerRenderLayer();
			SlimedDoorBlock.registerRenderLayer();
			SlimedChairBlock.registerRenderLayer();
			SlimedTableBlock.registerRenderLayer();
			SlimedLadderBlock.registerRenderLayer();
			FrozenDoorBlock.registerRenderLayer();
			FrozenChairBlock.registerRenderLayer();
			FrozenTableBlock.registerRenderLayer();
			FrozenLadderBlock.registerRenderLayer();
			NightAltarBlock.registerRenderLayer();
			NightAltarActivatedBlock.registerRenderLayer();
			StoneBrickPillarIgnitedBlock.registerRenderLayer();
			StoneBrickPillarBlock.registerRenderLayer();
			PhantomLanternBlock.registerRenderLayer();
			EnderLanternBlock.registerRenderLayer();
			HoglinLanternBlock.registerRenderLayer();
			SlimeRootBlockBlock.registerRenderLayer();
			HealCampFireBlock.registerRenderLayer();
			ShieldCampFireBlock.registerRenderLayer();
			BrokenRadioBlock.registerRenderLayer();
			SomniumExtractorBlock.registerRenderLayer();
			ArcaneWorkbenchBlock.registerRenderLayer();
			ResearchTableBlock.registerRenderLayer();
			CrystalCutterBlock.registerRenderLayer();
			SomniumInfuserBlock.registerRenderLayer();
			MortarAndPestleBlock.registerRenderLayer();
			RottenLeaveBlock.registerRenderLayer();
			InfectedGrassBlock.registerRenderLayer();
			LoranFlowerBlock.registerRenderLayer();
			GulomPlantBlock.registerRenderLayer();
			RalomPlantBlock.registerRenderLayer();
			FortisUltimaBlock.registerRenderLayer();
			OpiaShroomBlock.registerRenderLayer();
			ThunderFlowerBlock.registerRenderLayer();
			LercasUmbrellaBlock.registerRenderLayer();
			SralaShroomBlock.registerRenderLayer();
			SaturniaVersaBlock.registerRenderLayer();
			LumusMaximusBlock.registerRenderLayer();
			VeraLesusBlock.registerRenderLayer();
			OctavysMagynisiusBlock.registerRenderLayer();
			CaecusVersaBlock.registerRenderLayer();
			FlosVitaeBlock.registerRenderLayer();
			LeraExiliarisBlock.registerRenderLayer();
			IgnetarisVersaBlock.registerRenderLayer();
			GoralysLasusBlock.registerRenderLayer();
			WartRootBlock.registerRenderLayer();
			LoranBush2Block.registerRenderLayer();
			LoranBushBlock.registerRenderLayer();
			TenuemFireBlock.registerRenderLayer();
			AnimaFireBlock.registerRenderLayer();
			SlimedVitaeBlock.registerRenderLayer();
			IceRankBlock.registerRenderLayer();
			IcoraFlowerBlock.registerRenderLayer();
			TeslaRankBlock.registerRenderLayer();
			IcelaRankBlock.registerRenderLayer();
			RottenRankBlock.registerRenderLayer();
			WartRankBlock.registerRenderLayer();
			WartRankEndBlock.registerRenderLayer();
			GrassSmallBlock.registerRenderLayer();
			GrassMiddleBlock.registerRenderLayer();
			GrassBigBlock.registerRenderLayer();
			TallGlowShroomBlock.registerRenderLayer();
			GlowShroomBlock.registerRenderLayer();
			TallRubShroomBlock.registerRenderLayer();
			RubShroomBlock.registerRenderLayer();
			VertaCelsiusBlock.registerRenderLayer();
			SlimedLogFungiBlock.registerRenderLayer();
			BlaruLogFungiBlock.registerRenderLayer();
			JungleLogFungiBlock.registerRenderLayer();
			BogLogFungiBlock.registerRenderLayer();
			RumaLogFungiBlock.registerRenderLayer();
			RumaLogFungi2Block.registerRenderLayer();
			SalLogFungiBlock.registerRenderLayer();
			MiniStone1Block.registerRenderLayer();
			BogVineBlock.registerRenderLayer();
			TantraVineBlock.registerRenderLayer();
			SalVineBlock.registerRenderLayer();
			RoggenVineBlock.registerRenderLayer();
			RottenLogVineBlock.registerRenderLayer();
			SlimedLogVineBlock.registerRenderLayer();
			JungleLogVineBlock.registerRenderLayer();
			FrozenLogVineBlock.registerRenderLayer();
			RumaLogVineBlock.registerRenderLayer();
			BlaruLogVineBlock.registerRenderLayer();
			JungleVineBlock.registerRenderLayer();
			BlaruVineBlock.registerRenderLayer();
			LorkaVineBlock.registerRenderLayer();
			SlimedLogCrystalBlock.registerRenderLayer();
			TantraGrassSmallBlock.registerRenderLayer();
			TantraGrassMiddleBlock.registerRenderLayer();
			TantraGrassBigBlock.registerRenderLayer();
			LazarusGrassBlock.registerRenderLayer();
			LumusGrassBlock.registerRenderLayer();
			LumusFlowerBlock.registerRenderLayer();
			LumusRankBlock.registerRenderLayer();
			LumusFruitBlock.registerRenderLayer();
			VealusMeramusBlock.registerRenderLayer();
			CrimsonCrystalOreBlock.registerRenderLayer();
			WarpedCrystalOreBlock.registerRenderLayer();
			AurelCrystalOreBlock.registerRenderLayer();
			CavernaCrystalOreBlock.registerRenderLayer();
			EnderCrystalOreBlock.registerRenderLayer();
			FrostCrystalOreBlock.registerRenderLayer();
			AbyssCrystalOreBlock.registerRenderLayer();
			HollowCrystalOreBlock.registerRenderLayer();
			ExoliusPlantBlock.registerRenderLayer();
			YoungExoliusPlantBlock.registerRenderLayer();
			BlaruLeaveCarpetBlock.registerRenderLayer();
			JungleLeaveCarpetBlock.registerRenderLayer();
			SlimedCarpetBlock.registerRenderLayer();
			LungoRankBlock.registerRenderLayer();
			GlowingBlaruMossBlock.registerRenderLayer();
			AurelCaveMossBlock.registerRenderLayer();
			AurelShroomBlock.registerRenderLayer();
			AurelLeaveCarpetBlock.registerRenderLayer();
			AurelRankBlock.registerRenderLayer();
			BlaruCaveMossBlock.registerRenderLayer();
			EcholotTopBlock.registerRenderLayer();
			EcholotMiddleBlock.registerRenderLayer();
			EcholotBottomBlock.registerRenderLayer();
			LumaGrassBlock.registerRenderLayer();
			PhantomHangingLanternBlock.registerRenderLayer();
			EnderHangingLanternBlock.registerRenderLayer();
			HoglinHangingLanternBlock.registerRenderLayer();
			RaptorEggBlock.registerRenderLayer();
			WaterEcholotTopBlock.registerRenderLayer();
			WaterEcholotMiddleBlock.registerRenderLayer();
			WaterEcholotBottomBlock.registerRenderLayer();
			SlimedRankBlock.registerRenderLayer();
		}

		@SubscribeEvent
		public static void blockColorLoad(ColorHandlerEvent.Block event) {
			InfectedGrassBlock.blockColorLoad(event);
			GrassSmallBlock.blockColorLoad(event);
			GrassMiddleBlock.blockColorLoad(event);
			GrassBigBlock.blockColorLoad(event);
		}

		@SubscribeEvent
		public static void itemColorLoad(ColorHandlerEvent.Item event) {
			InfectedGrassBlock.itemColorLoad(event);
			GrassSmallBlock.itemColorLoad(event);
			GrassMiddleBlock.itemColorLoad(event);
			GrassBigBlock.itemColorLoad(event);
		}
	}
}
