@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.yezon.theabyss.configuration;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;